/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.constraint.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Complex Pattern Statements</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.constraint.mydsl.myDsl.ComplexPatternStatements#getComplexPatternType <em>Complex Pattern Type</em>}</li>
 * </ul>
 *
 * @see org.xtext.constraint.mydsl.myDsl.MyDslPackage#getComplexPatternStatements()
 * @model
 * @generated
 */
public interface ComplexPatternStatements extends EObject
{
  /**
   * Returns the value of the '<em><b>Complex Pattern Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Complex Pattern Type</em>' containment reference.
   * @see #setComplexPatternType(ComplexPatternType)
   * @see org.xtext.constraint.mydsl.myDsl.MyDslPackage#getComplexPatternStatements_ComplexPatternType()
   * @model containment="true"
   * @generated
   */
  ComplexPatternType getComplexPatternType();

  /**
   * Sets the value of the '{@link org.xtext.constraint.mydsl.myDsl.ComplexPatternStatements#getComplexPatternType <em>Complex Pattern Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Complex Pattern Type</em>' containment reference.
   * @see #getComplexPatternType()
   * @generated
   */
  void setComplexPatternType(ComplexPatternType value);

} // ComplexPatternStatements
