/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.constraint.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Complex Pattern Options</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.constraint.mydsl.myDsl.ComplexPatternOptions#getSeceondEvent <em>Seceond Event</em>}</li>
 *   <li>{@link org.xtext.constraint.mydsl.myDsl.ComplexPatternOptions#getGreedyQuantifiers <em>Greedy Quantifiers</em>}</li>
 * </ul>
 *
 * @see org.xtext.constraint.mydsl.myDsl.MyDslPackage#getComplexPatternOptions()
 * @model
 * @generated
 */
public interface ComplexPatternOptions extends EObject
{
  /**
   * Returns the value of the '<em><b>Seceond Event</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Seceond Event</em>' reference.
   * @see #setSeceondEvent(InputStatement)
   * @see org.xtext.constraint.mydsl.myDsl.MyDslPackage#getComplexPatternOptions_SeceondEvent()
   * @model
   * @generated
   */
  InputStatement getSeceondEvent();

  /**
   * Sets the value of the '{@link org.xtext.constraint.mydsl.myDsl.ComplexPatternOptions#getSeceondEvent <em>Seceond Event</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Seceond Event</em>' reference.
   * @see #getSeceondEvent()
   * @generated
   */
  void setSeceondEvent(InputStatement value);

  /**
   * Returns the value of the '<em><b>Greedy Quantifiers</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.constraint.mydsl.myDsl.GreedyQuantifiers}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Greedy Quantifiers</em>' attribute.
   * @see org.xtext.constraint.mydsl.myDsl.GreedyQuantifiers
   * @see #setGreedyQuantifiers(GreedyQuantifiers)
   * @see org.xtext.constraint.mydsl.myDsl.MyDslPackage#getComplexPatternOptions_GreedyQuantifiers()
   * @model
   * @generated
   */
  GreedyQuantifiers getGreedyQuantifiers();

  /**
   * Sets the value of the '{@link org.xtext.constraint.mydsl.myDsl.ComplexPatternOptions#getGreedyQuantifiers <em>Greedy Quantifiers</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Greedy Quantifiers</em>' attribute.
   * @see org.xtext.constraint.mydsl.myDsl.GreedyQuantifiers
   * @see #getGreedyQuantifiers()
   * @generated
   */
  void setGreedyQuantifiers(GreedyQuantifiers value);

} // ComplexPatternOptions
