/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.constraint.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Complex Pattern Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.constraint.mydsl.myDsl.ComplexPatternType#getFirstEvent <em>First Event</em>}</li>
 *   <li>{@link org.xtext.constraint.mydsl.myDsl.ComplexPatternType#getGreedyQuantifiers <em>Greedy Quantifiers</em>}</li>
 *   <li>{@link org.xtext.constraint.mydsl.myDsl.ComplexPatternType#getComplexPatternOptions <em>Complex Pattern Options</em>}</li>
 * </ul>
 *
 * @see org.xtext.constraint.mydsl.myDsl.MyDslPackage#getComplexPatternType()
 * @model
 * @generated
 */
public interface ComplexPatternType extends EObject
{
  /**
   * Returns the value of the '<em><b>First Event</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>First Event</em>' reference.
   * @see #setFirstEvent(InputStatement)
   * @see org.xtext.constraint.mydsl.myDsl.MyDslPackage#getComplexPatternType_FirstEvent()
   * @model
   * @generated
   */
  InputStatement getFirstEvent();

  /**
   * Sets the value of the '{@link org.xtext.constraint.mydsl.myDsl.ComplexPatternType#getFirstEvent <em>First Event</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>First Event</em>' reference.
   * @see #getFirstEvent()
   * @generated
   */
  void setFirstEvent(InputStatement value);

  /**
   * Returns the value of the '<em><b>Greedy Quantifiers</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.constraint.mydsl.myDsl.GreedyQuantifiers}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Greedy Quantifiers</em>' attribute.
   * @see org.xtext.constraint.mydsl.myDsl.GreedyQuantifiers
   * @see #setGreedyQuantifiers(GreedyQuantifiers)
   * @see org.xtext.constraint.mydsl.myDsl.MyDslPackage#getComplexPatternType_GreedyQuantifiers()
   * @model
   * @generated
   */
  GreedyQuantifiers getGreedyQuantifiers();

  /**
   * Sets the value of the '{@link org.xtext.constraint.mydsl.myDsl.ComplexPatternType#getGreedyQuantifiers <em>Greedy Quantifiers</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Greedy Quantifiers</em>' attribute.
   * @see org.xtext.constraint.mydsl.myDsl.GreedyQuantifiers
   * @see #getGreedyQuantifiers()
   * @generated
   */
  void setGreedyQuantifiers(GreedyQuantifiers value);

  /**
   * Returns the value of the '<em><b>Complex Pattern Options</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.constraint.mydsl.myDsl.ComplexPatternOptions}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Complex Pattern Options</em>' containment reference list.
   * @see org.xtext.constraint.mydsl.myDsl.MyDslPackage#getComplexPatternType_ComplexPatternOptions()
   * @model containment="true"
   * @generated
   */
  EList<ComplexPatternOptions> getComplexPatternOptions();

} // ComplexPatternType
