/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.constraint.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Input Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.constraint.mydsl.myDsl.InputStatement#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.constraint.mydsl.myDsl.InputStatement#getProperty <em>Property</em>}</li>
 *   <li>{@link org.xtext.constraint.mydsl.myDsl.InputStatement#getComparisonOperator <em>Comparison Operator</em>}</li>
 *   <li>{@link org.xtext.constraint.mydsl.myDsl.InputStatement#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see org.xtext.constraint.mydsl.myDsl.MyDslPackage#getInputStatement()
 * @model
 * @generated
 */
public interface InputStatement extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.constraint.mydsl.myDsl.MyDslPackage#getInputStatement_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.constraint.mydsl.myDsl.InputStatement#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Property</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Property</em>' attribute.
   * @see #setProperty(String)
   * @see org.xtext.constraint.mydsl.myDsl.MyDslPackage#getInputStatement_Property()
   * @model
   * @generated
   */
  String getProperty();

  /**
   * Sets the value of the '{@link org.xtext.constraint.mydsl.myDsl.InputStatement#getProperty <em>Property</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Property</em>' attribute.
   * @see #getProperty()
   * @generated
   */
  void setProperty(String value);

  /**
   * Returns the value of the '<em><b>Comparison Operator</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.constraint.mydsl.myDsl.ComparisonOperator}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comparison Operator</em>' attribute.
   * @see org.xtext.constraint.mydsl.myDsl.ComparisonOperator
   * @see #setComparisonOperator(ComparisonOperator)
   * @see org.xtext.constraint.mydsl.myDsl.MyDslPackage#getInputStatement_ComparisonOperator()
   * @model
   * @generated
   */
  ComparisonOperator getComparisonOperator();

  /**
   * Sets the value of the '{@link org.xtext.constraint.mydsl.myDsl.InputStatement#getComparisonOperator <em>Comparison Operator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Comparison Operator</em>' attribute.
   * @see org.xtext.constraint.mydsl.myDsl.ComparisonOperator
   * @see #getComparisonOperator()
   * @generated
   */
  void setComparisonOperator(ComparisonOperator value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(ValueOptions)
   * @see org.xtext.constraint.mydsl.myDsl.MyDslPackage#getInputStatement_Value()
   * @model containment="true"
   * @generated
   */
  ValueOptions getValue();

  /**
   * Sets the value of the '{@link org.xtext.constraint.mydsl.myDsl.InputStatement#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(ValueOptions value);

} // InputStatement
