/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.constraint.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Min Duration</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.constraint.mydsl.myDsl.MyDslPackage#getMinDuration()
 * @model
 * @generated
 */
public interface MinDuration extends Timer
{
} // MinDuration
