/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.constraint.mydsl.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.constraint.mydsl.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/constraint/mydsl/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.constraint.mydsl.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.constraint.mydsl.myDsl.impl.PatternModelImpl <em>Pattern Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.constraint.mydsl.myDsl.impl.PatternModelImpl
   * @see org.xtext.constraint.mydsl.myDsl.impl.MyDslPackageImpl#getPatternModel()
   * @generated
   */
  int PATTERN_MODEL = 0;

  /**
   * The feature id for the '<em><b>Elements</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATTERN_MODEL__ELEMENTS = 0;

  /**
   * The number of structural features of the '<em>Pattern Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATTERN_MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.constraint.mydsl.myDsl.impl.QueryInitializationImpl <em>Query Initialization</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.constraint.mydsl.myDsl.impl.QueryInitializationImpl
   * @see org.xtext.constraint.mydsl.myDsl.impl.MyDslPackageImpl#getQueryInitialization()
   * @generated
   */
  int QUERY_INITIALIZATION = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY_INITIALIZATION__NAME = 0;

  /**
   * The feature id for the '<em><b>Time Window</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY_INITIALIZATION__TIME_WINDOW = 1;

  /**
   * The feature id for the '<em><b>Input Statements</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY_INITIALIZATION__INPUT_STATEMENTS = 2;

  /**
   * The number of structural features of the '<em>Query Initialization</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int QUERY_INITIALIZATION_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.constraint.mydsl.myDsl.impl.PatternInitializationImpl <em>Pattern Initialization</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.constraint.mydsl.myDsl.impl.PatternInitializationImpl
   * @see org.xtext.constraint.mydsl.myDsl.impl.MyDslPackageImpl#getPatternInitialization()
   * @generated
   */
  int PATTERN_INITIALIZATION = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATTERN_INITIALIZATION__NAME = 0;

  /**
   * The feature id for the '<em><b>Time Window</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATTERN_INITIALIZATION__TIME_WINDOW = 1;

  /**
   * The feature id for the '<em><b>Input Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATTERN_INITIALIZATION__INPUT_STATEMENTS = 2;

  /**
   * The feature id for the '<em><b>Pattern Statements</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATTERN_INITIALIZATION__PATTERN_STATEMENTS = 3;

  /**
   * The number of structural features of the '<em>Pattern Initialization</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATTERN_INITIALIZATION_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.constraint.mydsl.myDsl.impl.ComplexInitializationImpl <em>Complex Initialization</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.constraint.mydsl.myDsl.impl.ComplexInitializationImpl
   * @see org.xtext.constraint.mydsl.myDsl.impl.MyDslPackageImpl#getComplexInitialization()
   * @generated
   */
  int COMPLEX_INITIALIZATION = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEX_INITIALIZATION__NAME = 0;

  /**
   * The feature id for the '<em><b>Time Window</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEX_INITIALIZATION__TIME_WINDOW = 1;

  /**
   * The feature id for the '<em><b>Input Statements</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEX_INITIALIZATION__INPUT_STATEMENTS = 2;

  /**
   * The feature id for the '<em><b>Complex Pattern Statements</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEX_INITIALIZATION__COMPLEX_PATTERN_STATEMENTS = 3;

  /**
   * The number of structural features of the '<em>Complex Initialization</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEX_INITIALIZATION_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.constraint.mydsl.myDsl.impl.ComplexPatternStatementsImpl <em>Complex Pattern Statements</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.constraint.mydsl.myDsl.impl.ComplexPatternStatementsImpl
   * @see org.xtext.constraint.mydsl.myDsl.impl.MyDslPackageImpl#getComplexPatternStatements()
   * @generated
   */
  int COMPLEX_PATTERN_STATEMENTS = 4;

  /**
   * The feature id for the '<em><b>Complex Pattern Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEX_PATTERN_STATEMENTS__COMPLEX_PATTERN_TYPE = 0;

  /**
   * The number of structural features of the '<em>Complex Pattern Statements</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEX_PATTERN_STATEMENTS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.constraint.mydsl.myDsl.impl.ComplexPatternTypeImpl <em>Complex Pattern Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.constraint.mydsl.myDsl.impl.ComplexPatternTypeImpl
   * @see org.xtext.constraint.mydsl.myDsl.impl.MyDslPackageImpl#getComplexPatternType()
   * @generated
   */
  int COMPLEX_PATTERN_TYPE = 5;

  /**
   * The feature id for the '<em><b>First Event</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEX_PATTERN_TYPE__FIRST_EVENT = 0;

  /**
   * The feature id for the '<em><b>Greedy Quantifiers</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEX_PATTERN_TYPE__GREEDY_QUANTIFIERS = 1;

  /**
   * The feature id for the '<em><b>Complex Pattern Options</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEX_PATTERN_TYPE__COMPLEX_PATTERN_OPTIONS = 2;

  /**
   * The number of structural features of the '<em>Complex Pattern Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEX_PATTERN_TYPE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.constraint.mydsl.myDsl.impl.ComplexPatternOptionsImpl <em>Complex Pattern Options</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.constraint.mydsl.myDsl.impl.ComplexPatternOptionsImpl
   * @see org.xtext.constraint.mydsl.myDsl.impl.MyDslPackageImpl#getComplexPatternOptions()
   * @generated
   */
  int COMPLEX_PATTERN_OPTIONS = 6;

  /**
   * The feature id for the '<em><b>Seceond Event</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEX_PATTERN_OPTIONS__SECEOND_EVENT = 0;

  /**
   * The feature id for the '<em><b>Greedy Quantifiers</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEX_PATTERN_OPTIONS__GREEDY_QUANTIFIERS = 1;

  /**
   * The number of structural features of the '<em>Complex Pattern Options</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPLEX_PATTERN_OPTIONS_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.constraint.mydsl.myDsl.impl.InputStatementImpl <em>Input Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.constraint.mydsl.myDsl.impl.InputStatementImpl
   * @see org.xtext.constraint.mydsl.myDsl.impl.MyDslPackageImpl#getInputStatement()
   * @generated
   */
  int INPUT_STATEMENT = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT_STATEMENT__NAME = 0;

  /**
   * The feature id for the '<em><b>Property</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT_STATEMENT__PROPERTY = 1;

  /**
   * The feature id for the '<em><b>Comparison Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT_STATEMENT__COMPARISON_OPERATOR = 2;

  /**
   * The feature id for the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT_STATEMENT__VALUE = 3;

  /**
   * The number of structural features of the '<em>Input Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INPUT_STATEMENT_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.constraint.mydsl.myDsl.impl.PatternStatementImpl <em>Pattern Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.constraint.mydsl.myDsl.impl.PatternStatementImpl
   * @see org.xtext.constraint.mydsl.myDsl.impl.MyDslPackageImpl#getPatternStatement()
   * @generated
   */
  int PATTERN_STATEMENT = 8;

  /**
   * The feature id for the '<em><b>Pattern Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATTERN_STATEMENT__PATTERN_TYPE = 0;

  /**
   * The number of structural features of the '<em>Pattern Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATTERN_STATEMENT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.constraint.mydsl.myDsl.impl.PatternTypeImpl <em>Pattern Type</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.constraint.mydsl.myDsl.impl.PatternTypeImpl
   * @see org.xtext.constraint.mydsl.myDsl.impl.MyDslPackageImpl#getPatternType()
   * @generated
   */
  int PATTERN_TYPE = 9;

  /**
   * The feature id for the '<em><b>First Event</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATTERN_TYPE__FIRST_EVENT = 0;

  /**
   * The feature id for the '<em><b>Pattern Options</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATTERN_TYPE__PATTERN_OPTIONS = 1;

  /**
   * The number of structural features of the '<em>Pattern Type</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATTERN_TYPE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.constraint.mydsl.myDsl.impl.PatternOptionsImpl <em>Pattern Options</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.constraint.mydsl.myDsl.impl.PatternOptionsImpl
   * @see org.xtext.constraint.mydsl.myDsl.impl.MyDslPackageImpl#getPatternOptions()
   * @generated
   */
  int PATTERN_OPTIONS = 10;

  /**
   * The feature id for the '<em><b>Occurence At Least</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATTERN_OPTIONS__OCCURENCE_AT_LEAST = 0;

  /**
   * The feature id for the '<em><b>Occurence At Most</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATTERN_OPTIONS__OCCURENCE_AT_MOST = 1;

  /**
   * The feature id for the '<em><b>Occurence At Not Specific Time</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATTERN_OPTIONS__OCCURENCE_AT_NOT_SPECIFIC_TIME = 2;

  /**
   * The number of structural features of the '<em>Pattern Options</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PATTERN_OPTIONS_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.constraint.mydsl.myDsl.impl.OccurenceAtTimeImpl <em>Occurence At Time</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.constraint.mydsl.myDsl.impl.OccurenceAtTimeImpl
   * @see org.xtext.constraint.mydsl.myDsl.impl.MyDslPackageImpl#getOccurenceAtTime()
   * @generated
   */
  int OCCURENCE_AT_TIME = 11;

  /**
   * The feature id for the '<em><b>Min Duration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OCCURENCE_AT_TIME__MIN_DURATION = 0;

  /**
   * The feature id for the '<em><b>Max Duration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OCCURENCE_AT_TIME__MAX_DURATION = 1;

  /**
   * The number of structural features of the '<em>Occurence At Time</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OCCURENCE_AT_TIME_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.constraint.mydsl.myDsl.impl.OccurenceAtLeastImpl <em>Occurence At Least</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.constraint.mydsl.myDsl.impl.OccurenceAtLeastImpl
   * @see org.xtext.constraint.mydsl.myDsl.impl.MyDslPackageImpl#getOccurenceAtLeast()
   * @generated
   */
  int OCCURENCE_AT_LEAST = 12;

  /**
   * The feature id for the '<em><b>Seceond Event</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OCCURENCE_AT_LEAST__SECEOND_EVENT = 0;

  /**
   * The feature id for the '<em><b>Min Duration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OCCURENCE_AT_LEAST__MIN_DURATION = 1;

  /**
   * The number of structural features of the '<em>Occurence At Least</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OCCURENCE_AT_LEAST_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.constraint.mydsl.myDsl.impl.OccurenceAtMostImpl <em>Occurence At Most</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.constraint.mydsl.myDsl.impl.OccurenceAtMostImpl
   * @see org.xtext.constraint.mydsl.myDsl.impl.MyDslPackageImpl#getOccurenceAtMost()
   * @generated
   */
  int OCCURENCE_AT_MOST = 13;

  /**
   * The feature id for the '<em><b>Seceond Event</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OCCURENCE_AT_MOST__SECEOND_EVENT = 0;

  /**
   * The feature id for the '<em><b>Max Duration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OCCURENCE_AT_MOST__MAX_DURATION = 1;

  /**
   * The number of structural features of the '<em>Occurence At Most</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OCCURENCE_AT_MOST_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.constraint.mydsl.myDsl.impl.OccurenceAtNotSpecificTimeImpl <em>Occurence At Not Specific Time</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.constraint.mydsl.myDsl.impl.OccurenceAtNotSpecificTimeImpl
   * @see org.xtext.constraint.mydsl.myDsl.impl.MyDslPackageImpl#getOccurenceAtNotSpecificTime()
   * @generated
   */
  int OCCURENCE_AT_NOT_SPECIFIC_TIME = 14;

  /**
   * The feature id for the '<em><b>Seceond Event</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OCCURENCE_AT_NOT_SPECIFIC_TIME__SECEOND_EVENT = 0;

  /**
   * The number of structural features of the '<em>Occurence At Not Specific Time</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OCCURENCE_AT_NOT_SPECIFIC_TIME_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.constraint.mydsl.myDsl.impl.TimerImpl <em>Timer</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.constraint.mydsl.myDsl.impl.TimerImpl
   * @see org.xtext.constraint.mydsl.myDsl.impl.MyDslPackageImpl#getTimer()
   * @generated
   */
  int TIMER = 15;

  /**
   * The feature id for the '<em><b>Timer Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIMER__TIMER_TYPE = 0;

  /**
   * The feature id for the '<em><b>Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIMER__TIME = 1;

  /**
   * The feature id for the '<em><b>Time Unit</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIMER__TIME_UNIT = 2;

  /**
   * The number of structural features of the '<em>Timer</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIMER_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.constraint.mydsl.myDsl.impl.MaxDurationImpl <em>Max Duration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.constraint.mydsl.myDsl.impl.MaxDurationImpl
   * @see org.xtext.constraint.mydsl.myDsl.impl.MyDslPackageImpl#getMaxDuration()
   * @generated
   */
  int MAX_DURATION = 16;

  /**
   * The feature id for the '<em><b>Timer Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAX_DURATION__TIMER_TYPE = TIMER__TIMER_TYPE;

  /**
   * The feature id for the '<em><b>Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAX_DURATION__TIME = TIMER__TIME;

  /**
   * The feature id for the '<em><b>Time Unit</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAX_DURATION__TIME_UNIT = TIMER__TIME_UNIT;

  /**
   * The number of structural features of the '<em>Max Duration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAX_DURATION_FEATURE_COUNT = TIMER_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.constraint.mydsl.myDsl.impl.MinDurationImpl <em>Min Duration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.constraint.mydsl.myDsl.impl.MinDurationImpl
   * @see org.xtext.constraint.mydsl.myDsl.impl.MyDslPackageImpl#getMinDuration()
   * @generated
   */
  int MIN_DURATION = 17;

  /**
   * The feature id for the '<em><b>Timer Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MIN_DURATION__TIMER_TYPE = TIMER__TIMER_TYPE;

  /**
   * The feature id for the '<em><b>Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MIN_DURATION__TIME = TIMER__TIME;

  /**
   * The feature id for the '<em><b>Time Unit</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MIN_DURATION__TIME_UNIT = TIMER__TIME_UNIT;

  /**
   * The number of structural features of the '<em>Min Duration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MIN_DURATION_FEATURE_COUNT = TIMER_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.xtext.constraint.mydsl.myDsl.impl.TimeWindowImpl <em>Time Window</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.constraint.mydsl.myDsl.impl.TimeWindowImpl
   * @see org.xtext.constraint.mydsl.myDsl.impl.MyDslPackageImpl#getTimeWindow()
   * @generated
   */
  int TIME_WINDOW = 18;

  /**
   * The feature id for the '<em><b>Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME_WINDOW__TIME = 0;

  /**
   * The feature id for the '<em><b>Time Unit</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME_WINDOW__TIME_UNIT = 1;

  /**
   * The number of structural features of the '<em>Time Window</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TIME_WINDOW_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.constraint.mydsl.myDsl.impl.ValueOptionsImpl <em>Value Options</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.constraint.mydsl.myDsl.impl.ValueOptionsImpl
   * @see org.xtext.constraint.mydsl.myDsl.impl.MyDslPackageImpl#getValueOptions()
   * @generated
   */
  int VALUE_OPTIONS = 19;

  /**
   * The feature id for the '<em><b>String Literal</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE_OPTIONS__STRING_LITERAL = 0;

  /**
   * The feature id for the '<em><b>Number Literal</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE_OPTIONS__NUMBER_LITERAL = 1;

  /**
   * The feature id for the '<em><b>Text Literal</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE_OPTIONS__TEXT_LITERAL = 2;

  /**
   * The number of structural features of the '<em>Value Options</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE_OPTIONS_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.constraint.mydsl.myDsl.impl.StringLiteralImpl <em>String Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.constraint.mydsl.myDsl.impl.StringLiteralImpl
   * @see org.xtext.constraint.mydsl.myDsl.impl.MyDslPackageImpl#getStringLiteral()
   * @generated
   */
  int STRING_LITERAL = 20;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_LITERAL__VALUE = 0;

  /**
   * The number of structural features of the '<em>String Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STRING_LITERAL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.constraint.mydsl.myDsl.impl.NumberLiteralImpl <em>Number Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.constraint.mydsl.myDsl.impl.NumberLiteralImpl
   * @see org.xtext.constraint.mydsl.myDsl.impl.MyDslPackageImpl#getNumberLiteral()
   * @generated
   */
  int NUMBER_LITERAL = 21;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER_LITERAL__VALUE = 0;

  /**
   * The number of structural features of the '<em>Number Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NUMBER_LITERAL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.constraint.mydsl.myDsl.impl.TextLiteralImpl <em>Text Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.constraint.mydsl.myDsl.impl.TextLiteralImpl
   * @see org.xtext.constraint.mydsl.myDsl.impl.MyDslPackageImpl#getTextLiteral()
   * @generated
   */
  int TEXT_LITERAL = 22;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_LITERAL__VALUE = 0;

  /**
   * The number of structural features of the '<em>Text Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TEXT_LITERAL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.constraint.mydsl.myDsl.ComparisonOperator <em>Comparison Operator</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.constraint.mydsl.myDsl.ComparisonOperator
   * @see org.xtext.constraint.mydsl.myDsl.impl.MyDslPackageImpl#getComparisonOperator()
   * @generated
   */
  int COMPARISON_OPERATOR = 23;

  /**
   * The meta object id for the '{@link org.xtext.constraint.mydsl.myDsl.TimeUnit <em>Time Unit</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.constraint.mydsl.myDsl.TimeUnit
   * @see org.xtext.constraint.mydsl.myDsl.impl.MyDslPackageImpl#getTimeUnit()
   * @generated
   */
  int TIME_UNIT = 24;

  /**
   * The meta object id for the '{@link org.xtext.constraint.mydsl.myDsl.GreedyQuantifiers <em>Greedy Quantifiers</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.constraint.mydsl.myDsl.GreedyQuantifiers
   * @see org.xtext.constraint.mydsl.myDsl.impl.MyDslPackageImpl#getGreedyQuantifiers()
   * @generated
   */
  int GREEDY_QUANTIFIERS = 25;


  /**
   * Returns the meta object for class '{@link org.xtext.constraint.mydsl.myDsl.PatternModel <em>Pattern Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Pattern Model</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.PatternModel
   * @generated
   */
  EClass getPatternModel();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.constraint.mydsl.myDsl.PatternModel#getElements <em>Elements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Elements</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.PatternModel#getElements()
   * @see #getPatternModel()
   * @generated
   */
  EReference getPatternModel_Elements();

  /**
   * Returns the meta object for class '{@link org.xtext.constraint.mydsl.myDsl.QueryInitialization <em>Query Initialization</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Query Initialization</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.QueryInitialization
   * @generated
   */
  EClass getQueryInitialization();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.constraint.mydsl.myDsl.QueryInitialization#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.QueryInitialization#getName()
   * @see #getQueryInitialization()
   * @generated
   */
  EAttribute getQueryInitialization_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.constraint.mydsl.myDsl.QueryInitialization#getTimeWindow <em>Time Window</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Time Window</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.QueryInitialization#getTimeWindow()
   * @see #getQueryInitialization()
   * @generated
   */
  EReference getQueryInitialization_TimeWindow();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.constraint.mydsl.myDsl.QueryInitialization#getInputStatements <em>Input Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Input Statements</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.QueryInitialization#getInputStatements()
   * @see #getQueryInitialization()
   * @generated
   */
  EReference getQueryInitialization_InputStatements();

  /**
   * Returns the meta object for class '{@link org.xtext.constraint.mydsl.myDsl.PatternInitialization <em>Pattern Initialization</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Pattern Initialization</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.PatternInitialization
   * @generated
   */
  EClass getPatternInitialization();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.constraint.mydsl.myDsl.PatternInitialization#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.PatternInitialization#getName()
   * @see #getPatternInitialization()
   * @generated
   */
  EAttribute getPatternInitialization_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.constraint.mydsl.myDsl.PatternInitialization#getTimeWindow <em>Time Window</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Time Window</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.PatternInitialization#getTimeWindow()
   * @see #getPatternInitialization()
   * @generated
   */
  EReference getPatternInitialization_TimeWindow();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.constraint.mydsl.myDsl.PatternInitialization#getInputStatements <em>Input Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Input Statements</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.PatternInitialization#getInputStatements()
   * @see #getPatternInitialization()
   * @generated
   */
  EReference getPatternInitialization_InputStatements();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.constraint.mydsl.myDsl.PatternInitialization#getPatternStatements <em>Pattern Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Pattern Statements</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.PatternInitialization#getPatternStatements()
   * @see #getPatternInitialization()
   * @generated
   */
  EReference getPatternInitialization_PatternStatements();

  /**
   * Returns the meta object for class '{@link org.xtext.constraint.mydsl.myDsl.ComplexInitialization <em>Complex Initialization</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Complex Initialization</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.ComplexInitialization
   * @generated
   */
  EClass getComplexInitialization();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.constraint.mydsl.myDsl.ComplexInitialization#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.ComplexInitialization#getName()
   * @see #getComplexInitialization()
   * @generated
   */
  EAttribute getComplexInitialization_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.constraint.mydsl.myDsl.ComplexInitialization#getTimeWindow <em>Time Window</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Time Window</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.ComplexInitialization#getTimeWindow()
   * @see #getComplexInitialization()
   * @generated
   */
  EReference getComplexInitialization_TimeWindow();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.constraint.mydsl.myDsl.ComplexInitialization#getInputStatements <em>Input Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Input Statements</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.ComplexInitialization#getInputStatements()
   * @see #getComplexInitialization()
   * @generated
   */
  EReference getComplexInitialization_InputStatements();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.constraint.mydsl.myDsl.ComplexInitialization#getComplexPatternStatements <em>Complex Pattern Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Complex Pattern Statements</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.ComplexInitialization#getComplexPatternStatements()
   * @see #getComplexInitialization()
   * @generated
   */
  EReference getComplexInitialization_ComplexPatternStatements();

  /**
   * Returns the meta object for class '{@link org.xtext.constraint.mydsl.myDsl.ComplexPatternStatements <em>Complex Pattern Statements</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Complex Pattern Statements</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.ComplexPatternStatements
   * @generated
   */
  EClass getComplexPatternStatements();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.constraint.mydsl.myDsl.ComplexPatternStatements#getComplexPatternType <em>Complex Pattern Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Complex Pattern Type</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.ComplexPatternStatements#getComplexPatternType()
   * @see #getComplexPatternStatements()
   * @generated
   */
  EReference getComplexPatternStatements_ComplexPatternType();

  /**
   * Returns the meta object for class '{@link org.xtext.constraint.mydsl.myDsl.ComplexPatternType <em>Complex Pattern Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Complex Pattern Type</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.ComplexPatternType
   * @generated
   */
  EClass getComplexPatternType();

  /**
   * Returns the meta object for the reference '{@link org.xtext.constraint.mydsl.myDsl.ComplexPatternType#getFirstEvent <em>First Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>First Event</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.ComplexPatternType#getFirstEvent()
   * @see #getComplexPatternType()
   * @generated
   */
  EReference getComplexPatternType_FirstEvent();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.constraint.mydsl.myDsl.ComplexPatternType#getGreedyQuantifiers <em>Greedy Quantifiers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Greedy Quantifiers</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.ComplexPatternType#getGreedyQuantifiers()
   * @see #getComplexPatternType()
   * @generated
   */
  EAttribute getComplexPatternType_GreedyQuantifiers();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.constraint.mydsl.myDsl.ComplexPatternType#getComplexPatternOptions <em>Complex Pattern Options</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Complex Pattern Options</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.ComplexPatternType#getComplexPatternOptions()
   * @see #getComplexPatternType()
   * @generated
   */
  EReference getComplexPatternType_ComplexPatternOptions();

  /**
   * Returns the meta object for class '{@link org.xtext.constraint.mydsl.myDsl.ComplexPatternOptions <em>Complex Pattern Options</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Complex Pattern Options</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.ComplexPatternOptions
   * @generated
   */
  EClass getComplexPatternOptions();

  /**
   * Returns the meta object for the reference '{@link org.xtext.constraint.mydsl.myDsl.ComplexPatternOptions#getSeceondEvent <em>Seceond Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Seceond Event</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.ComplexPatternOptions#getSeceondEvent()
   * @see #getComplexPatternOptions()
   * @generated
   */
  EReference getComplexPatternOptions_SeceondEvent();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.constraint.mydsl.myDsl.ComplexPatternOptions#getGreedyQuantifiers <em>Greedy Quantifiers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Greedy Quantifiers</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.ComplexPatternOptions#getGreedyQuantifiers()
   * @see #getComplexPatternOptions()
   * @generated
   */
  EAttribute getComplexPatternOptions_GreedyQuantifiers();

  /**
   * Returns the meta object for class '{@link org.xtext.constraint.mydsl.myDsl.InputStatement <em>Input Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Input Statement</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.InputStatement
   * @generated
   */
  EClass getInputStatement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.constraint.mydsl.myDsl.InputStatement#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.InputStatement#getName()
   * @see #getInputStatement()
   * @generated
   */
  EAttribute getInputStatement_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.constraint.mydsl.myDsl.InputStatement#getProperty <em>Property</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Property</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.InputStatement#getProperty()
   * @see #getInputStatement()
   * @generated
   */
  EAttribute getInputStatement_Property();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.constraint.mydsl.myDsl.InputStatement#getComparisonOperator <em>Comparison Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Comparison Operator</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.InputStatement#getComparisonOperator()
   * @see #getInputStatement()
   * @generated
   */
  EAttribute getInputStatement_ComparisonOperator();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.constraint.mydsl.myDsl.InputStatement#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Value</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.InputStatement#getValue()
   * @see #getInputStatement()
   * @generated
   */
  EReference getInputStatement_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.constraint.mydsl.myDsl.PatternStatement <em>Pattern Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Pattern Statement</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.PatternStatement
   * @generated
   */
  EClass getPatternStatement();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.constraint.mydsl.myDsl.PatternStatement#getPatternType <em>Pattern Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Pattern Type</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.PatternStatement#getPatternType()
   * @see #getPatternStatement()
   * @generated
   */
  EReference getPatternStatement_PatternType();

  /**
   * Returns the meta object for class '{@link org.xtext.constraint.mydsl.myDsl.PatternType <em>Pattern Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Pattern Type</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.PatternType
   * @generated
   */
  EClass getPatternType();

  /**
   * Returns the meta object for the reference '{@link org.xtext.constraint.mydsl.myDsl.PatternType#getFirstEvent <em>First Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>First Event</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.PatternType#getFirstEvent()
   * @see #getPatternType()
   * @generated
   */
  EReference getPatternType_FirstEvent();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.constraint.mydsl.myDsl.PatternType#getPatternOptions <em>Pattern Options</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Pattern Options</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.PatternType#getPatternOptions()
   * @see #getPatternType()
   * @generated
   */
  EReference getPatternType_PatternOptions();

  /**
   * Returns the meta object for class '{@link org.xtext.constraint.mydsl.myDsl.PatternOptions <em>Pattern Options</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Pattern Options</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.PatternOptions
   * @generated
   */
  EClass getPatternOptions();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.constraint.mydsl.myDsl.PatternOptions#getOccurenceAtLeast <em>Occurence At Least</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Occurence At Least</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.PatternOptions#getOccurenceAtLeast()
   * @see #getPatternOptions()
   * @generated
   */
  EReference getPatternOptions_OccurenceAtLeast();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.constraint.mydsl.myDsl.PatternOptions#getOccurenceAtMost <em>Occurence At Most</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Occurence At Most</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.PatternOptions#getOccurenceAtMost()
   * @see #getPatternOptions()
   * @generated
   */
  EReference getPatternOptions_OccurenceAtMost();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.constraint.mydsl.myDsl.PatternOptions#getOccurenceAtNotSpecificTime <em>Occurence At Not Specific Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Occurence At Not Specific Time</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.PatternOptions#getOccurenceAtNotSpecificTime()
   * @see #getPatternOptions()
   * @generated
   */
  EReference getPatternOptions_OccurenceAtNotSpecificTime();

  /**
   * Returns the meta object for class '{@link org.xtext.constraint.mydsl.myDsl.OccurenceAtTime <em>Occurence At Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Occurence At Time</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.OccurenceAtTime
   * @generated
   */
  EClass getOccurenceAtTime();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.constraint.mydsl.myDsl.OccurenceAtTime#getMinDuration <em>Min Duration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Min Duration</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.OccurenceAtTime#getMinDuration()
   * @see #getOccurenceAtTime()
   * @generated
   */
  EReference getOccurenceAtTime_MinDuration();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.constraint.mydsl.myDsl.OccurenceAtTime#getMaxDuration <em>Max Duration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Max Duration</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.OccurenceAtTime#getMaxDuration()
   * @see #getOccurenceAtTime()
   * @generated
   */
  EReference getOccurenceAtTime_MaxDuration();

  /**
   * Returns the meta object for class '{@link org.xtext.constraint.mydsl.myDsl.OccurenceAtLeast <em>Occurence At Least</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Occurence At Least</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.OccurenceAtLeast
   * @generated
   */
  EClass getOccurenceAtLeast();

  /**
   * Returns the meta object for the reference '{@link org.xtext.constraint.mydsl.myDsl.OccurenceAtLeast#getSeceondEvent <em>Seceond Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Seceond Event</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.OccurenceAtLeast#getSeceondEvent()
   * @see #getOccurenceAtLeast()
   * @generated
   */
  EReference getOccurenceAtLeast_SeceondEvent();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.constraint.mydsl.myDsl.OccurenceAtLeast#getMinDuration <em>Min Duration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Min Duration</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.OccurenceAtLeast#getMinDuration()
   * @see #getOccurenceAtLeast()
   * @generated
   */
  EReference getOccurenceAtLeast_MinDuration();

  /**
   * Returns the meta object for class '{@link org.xtext.constraint.mydsl.myDsl.OccurenceAtMost <em>Occurence At Most</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Occurence At Most</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.OccurenceAtMost
   * @generated
   */
  EClass getOccurenceAtMost();

  /**
   * Returns the meta object for the reference '{@link org.xtext.constraint.mydsl.myDsl.OccurenceAtMost#getSeceondEvent <em>Seceond Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Seceond Event</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.OccurenceAtMost#getSeceondEvent()
   * @see #getOccurenceAtMost()
   * @generated
   */
  EReference getOccurenceAtMost_SeceondEvent();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.constraint.mydsl.myDsl.OccurenceAtMost#getMaxDuration <em>Max Duration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Max Duration</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.OccurenceAtMost#getMaxDuration()
   * @see #getOccurenceAtMost()
   * @generated
   */
  EReference getOccurenceAtMost_MaxDuration();

  /**
   * Returns the meta object for class '{@link org.xtext.constraint.mydsl.myDsl.OccurenceAtNotSpecificTime <em>Occurence At Not Specific Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Occurence At Not Specific Time</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.OccurenceAtNotSpecificTime
   * @generated
   */
  EClass getOccurenceAtNotSpecificTime();

  /**
   * Returns the meta object for the reference '{@link org.xtext.constraint.mydsl.myDsl.OccurenceAtNotSpecificTime#getSeceondEvent <em>Seceond Event</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Seceond Event</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.OccurenceAtNotSpecificTime#getSeceondEvent()
   * @see #getOccurenceAtNotSpecificTime()
   * @generated
   */
  EReference getOccurenceAtNotSpecificTime_SeceondEvent();

  /**
   * Returns the meta object for class '{@link org.xtext.constraint.mydsl.myDsl.Timer <em>Timer</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Timer</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.Timer
   * @generated
   */
  EClass getTimer();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.constraint.mydsl.myDsl.Timer#getTimerType <em>Timer Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Timer Type</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.Timer#getTimerType()
   * @see #getTimer()
   * @generated
   */
  EAttribute getTimer_TimerType();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.constraint.mydsl.myDsl.Timer#getTime <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Time</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.Timer#getTime()
   * @see #getTimer()
   * @generated
   */
  EAttribute getTimer_Time();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.constraint.mydsl.myDsl.Timer#getTimeUnit <em>Time Unit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Time Unit</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.Timer#getTimeUnit()
   * @see #getTimer()
   * @generated
   */
  EAttribute getTimer_TimeUnit();

  /**
   * Returns the meta object for class '{@link org.xtext.constraint.mydsl.myDsl.MaxDuration <em>Max Duration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Max Duration</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.MaxDuration
   * @generated
   */
  EClass getMaxDuration();

  /**
   * Returns the meta object for class '{@link org.xtext.constraint.mydsl.myDsl.MinDuration <em>Min Duration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Min Duration</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.MinDuration
   * @generated
   */
  EClass getMinDuration();

  /**
   * Returns the meta object for class '{@link org.xtext.constraint.mydsl.myDsl.TimeWindow <em>Time Window</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Time Window</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.TimeWindow
   * @generated
   */
  EClass getTimeWindow();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.constraint.mydsl.myDsl.TimeWindow#getTime <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Time</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.TimeWindow#getTime()
   * @see #getTimeWindow()
   * @generated
   */
  EAttribute getTimeWindow_Time();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.constraint.mydsl.myDsl.TimeWindow#getTimeUnit <em>Time Unit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Time Unit</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.TimeWindow#getTimeUnit()
   * @see #getTimeWindow()
   * @generated
   */
  EAttribute getTimeWindow_TimeUnit();

  /**
   * Returns the meta object for class '{@link org.xtext.constraint.mydsl.myDsl.ValueOptions <em>Value Options</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Value Options</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.ValueOptions
   * @generated
   */
  EClass getValueOptions();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.constraint.mydsl.myDsl.ValueOptions#getStringLiteral <em>String Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>String Literal</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.ValueOptions#getStringLiteral()
   * @see #getValueOptions()
   * @generated
   */
  EReference getValueOptions_StringLiteral();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.constraint.mydsl.myDsl.ValueOptions#getNumberLiteral <em>Number Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Number Literal</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.ValueOptions#getNumberLiteral()
   * @see #getValueOptions()
   * @generated
   */
  EReference getValueOptions_NumberLiteral();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.constraint.mydsl.myDsl.ValueOptions#getTextLiteral <em>Text Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Text Literal</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.ValueOptions#getTextLiteral()
   * @see #getValueOptions()
   * @generated
   */
  EReference getValueOptions_TextLiteral();

  /**
   * Returns the meta object for class '{@link org.xtext.constraint.mydsl.myDsl.StringLiteral <em>String Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>String Literal</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.StringLiteral
   * @generated
   */
  EClass getStringLiteral();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.constraint.mydsl.myDsl.StringLiteral#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.StringLiteral#getValue()
   * @see #getStringLiteral()
   * @generated
   */
  EAttribute getStringLiteral_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.constraint.mydsl.myDsl.NumberLiteral <em>Number Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Number Literal</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.NumberLiteral
   * @generated
   */
  EClass getNumberLiteral();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.constraint.mydsl.myDsl.NumberLiteral#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.NumberLiteral#getValue()
   * @see #getNumberLiteral()
   * @generated
   */
  EAttribute getNumberLiteral_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.constraint.mydsl.myDsl.TextLiteral <em>Text Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Text Literal</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.TextLiteral
   * @generated
   */
  EClass getTextLiteral();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.constraint.mydsl.myDsl.TextLiteral#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.TextLiteral#getValue()
   * @see #getTextLiteral()
   * @generated
   */
  EAttribute getTextLiteral_Value();

  /**
   * Returns the meta object for enum '{@link org.xtext.constraint.mydsl.myDsl.ComparisonOperator <em>Comparison Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Comparison Operator</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.ComparisonOperator
   * @generated
   */
  EEnum getComparisonOperator();

  /**
   * Returns the meta object for enum '{@link org.xtext.constraint.mydsl.myDsl.TimeUnit <em>Time Unit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Time Unit</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.TimeUnit
   * @generated
   */
  EEnum getTimeUnit();

  /**
   * Returns the meta object for enum '{@link org.xtext.constraint.mydsl.myDsl.GreedyQuantifiers <em>Greedy Quantifiers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Greedy Quantifiers</em>'.
   * @see org.xtext.constraint.mydsl.myDsl.GreedyQuantifiers
   * @generated
   */
  EEnum getGreedyQuantifiers();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.constraint.mydsl.myDsl.impl.PatternModelImpl <em>Pattern Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.constraint.mydsl.myDsl.impl.PatternModelImpl
     * @see org.xtext.constraint.mydsl.myDsl.impl.MyDslPackageImpl#getPatternModel()
     * @generated
     */
    EClass PATTERN_MODEL = eINSTANCE.getPatternModel();

    /**
     * The meta object literal for the '<em><b>Elements</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PATTERN_MODEL__ELEMENTS = eINSTANCE.getPatternModel_Elements();

    /**
     * The meta object literal for the '{@link org.xtext.constraint.mydsl.myDsl.impl.QueryInitializationImpl <em>Query Initialization</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.constraint.mydsl.myDsl.impl.QueryInitializationImpl
     * @see org.xtext.constraint.mydsl.myDsl.impl.MyDslPackageImpl#getQueryInitialization()
     * @generated
     */
    EClass QUERY_INITIALIZATION = eINSTANCE.getQueryInitialization();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute QUERY_INITIALIZATION__NAME = eINSTANCE.getQueryInitialization_Name();

    /**
     * The meta object literal for the '<em><b>Time Window</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QUERY_INITIALIZATION__TIME_WINDOW = eINSTANCE.getQueryInitialization_TimeWindow();

    /**
     * The meta object literal for the '<em><b>Input Statements</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference QUERY_INITIALIZATION__INPUT_STATEMENTS = eINSTANCE.getQueryInitialization_InputStatements();

    /**
     * The meta object literal for the '{@link org.xtext.constraint.mydsl.myDsl.impl.PatternInitializationImpl <em>Pattern Initialization</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.constraint.mydsl.myDsl.impl.PatternInitializationImpl
     * @see org.xtext.constraint.mydsl.myDsl.impl.MyDslPackageImpl#getPatternInitialization()
     * @generated
     */
    EClass PATTERN_INITIALIZATION = eINSTANCE.getPatternInitialization();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PATTERN_INITIALIZATION__NAME = eINSTANCE.getPatternInitialization_Name();

    /**
     * The meta object literal for the '<em><b>Time Window</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PATTERN_INITIALIZATION__TIME_WINDOW = eINSTANCE.getPatternInitialization_TimeWindow();

    /**
     * The meta object literal for the '<em><b>Input Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PATTERN_INITIALIZATION__INPUT_STATEMENTS = eINSTANCE.getPatternInitialization_InputStatements();

    /**
     * The meta object literal for the '<em><b>Pattern Statements</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PATTERN_INITIALIZATION__PATTERN_STATEMENTS = eINSTANCE.getPatternInitialization_PatternStatements();

    /**
     * The meta object literal for the '{@link org.xtext.constraint.mydsl.myDsl.impl.ComplexInitializationImpl <em>Complex Initialization</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.constraint.mydsl.myDsl.impl.ComplexInitializationImpl
     * @see org.xtext.constraint.mydsl.myDsl.impl.MyDslPackageImpl#getComplexInitialization()
     * @generated
     */
    EClass COMPLEX_INITIALIZATION = eINSTANCE.getComplexInitialization();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPLEX_INITIALIZATION__NAME = eINSTANCE.getComplexInitialization_Name();

    /**
     * The meta object literal for the '<em><b>Time Window</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPLEX_INITIALIZATION__TIME_WINDOW = eINSTANCE.getComplexInitialization_TimeWindow();

    /**
     * The meta object literal for the '<em><b>Input Statements</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPLEX_INITIALIZATION__INPUT_STATEMENTS = eINSTANCE.getComplexInitialization_InputStatements();

    /**
     * The meta object literal for the '<em><b>Complex Pattern Statements</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPLEX_INITIALIZATION__COMPLEX_PATTERN_STATEMENTS = eINSTANCE.getComplexInitialization_ComplexPatternStatements();

    /**
     * The meta object literal for the '{@link org.xtext.constraint.mydsl.myDsl.impl.ComplexPatternStatementsImpl <em>Complex Pattern Statements</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.constraint.mydsl.myDsl.impl.ComplexPatternStatementsImpl
     * @see org.xtext.constraint.mydsl.myDsl.impl.MyDslPackageImpl#getComplexPatternStatements()
     * @generated
     */
    EClass COMPLEX_PATTERN_STATEMENTS = eINSTANCE.getComplexPatternStatements();

    /**
     * The meta object literal for the '<em><b>Complex Pattern Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPLEX_PATTERN_STATEMENTS__COMPLEX_PATTERN_TYPE = eINSTANCE.getComplexPatternStatements_ComplexPatternType();

    /**
     * The meta object literal for the '{@link org.xtext.constraint.mydsl.myDsl.impl.ComplexPatternTypeImpl <em>Complex Pattern Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.constraint.mydsl.myDsl.impl.ComplexPatternTypeImpl
     * @see org.xtext.constraint.mydsl.myDsl.impl.MyDslPackageImpl#getComplexPatternType()
     * @generated
     */
    EClass COMPLEX_PATTERN_TYPE = eINSTANCE.getComplexPatternType();

    /**
     * The meta object literal for the '<em><b>First Event</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPLEX_PATTERN_TYPE__FIRST_EVENT = eINSTANCE.getComplexPatternType_FirstEvent();

    /**
     * The meta object literal for the '<em><b>Greedy Quantifiers</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPLEX_PATTERN_TYPE__GREEDY_QUANTIFIERS = eINSTANCE.getComplexPatternType_GreedyQuantifiers();

    /**
     * The meta object literal for the '<em><b>Complex Pattern Options</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPLEX_PATTERN_TYPE__COMPLEX_PATTERN_OPTIONS = eINSTANCE.getComplexPatternType_ComplexPatternOptions();

    /**
     * The meta object literal for the '{@link org.xtext.constraint.mydsl.myDsl.impl.ComplexPatternOptionsImpl <em>Complex Pattern Options</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.constraint.mydsl.myDsl.impl.ComplexPatternOptionsImpl
     * @see org.xtext.constraint.mydsl.myDsl.impl.MyDslPackageImpl#getComplexPatternOptions()
     * @generated
     */
    EClass COMPLEX_PATTERN_OPTIONS = eINSTANCE.getComplexPatternOptions();

    /**
     * The meta object literal for the '<em><b>Seceond Event</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPLEX_PATTERN_OPTIONS__SECEOND_EVENT = eINSTANCE.getComplexPatternOptions_SeceondEvent();

    /**
     * The meta object literal for the '<em><b>Greedy Quantifiers</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMPLEX_PATTERN_OPTIONS__GREEDY_QUANTIFIERS = eINSTANCE.getComplexPatternOptions_GreedyQuantifiers();

    /**
     * The meta object literal for the '{@link org.xtext.constraint.mydsl.myDsl.impl.InputStatementImpl <em>Input Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.constraint.mydsl.myDsl.impl.InputStatementImpl
     * @see org.xtext.constraint.mydsl.myDsl.impl.MyDslPackageImpl#getInputStatement()
     * @generated
     */
    EClass INPUT_STATEMENT = eINSTANCE.getInputStatement();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INPUT_STATEMENT__NAME = eINSTANCE.getInputStatement_Name();

    /**
     * The meta object literal for the '<em><b>Property</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INPUT_STATEMENT__PROPERTY = eINSTANCE.getInputStatement_Property();

    /**
     * The meta object literal for the '<em><b>Comparison Operator</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INPUT_STATEMENT__COMPARISON_OPERATOR = eINSTANCE.getInputStatement_ComparisonOperator();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INPUT_STATEMENT__VALUE = eINSTANCE.getInputStatement_Value();

    /**
     * The meta object literal for the '{@link org.xtext.constraint.mydsl.myDsl.impl.PatternStatementImpl <em>Pattern Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.constraint.mydsl.myDsl.impl.PatternStatementImpl
     * @see org.xtext.constraint.mydsl.myDsl.impl.MyDslPackageImpl#getPatternStatement()
     * @generated
     */
    EClass PATTERN_STATEMENT = eINSTANCE.getPatternStatement();

    /**
     * The meta object literal for the '<em><b>Pattern Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PATTERN_STATEMENT__PATTERN_TYPE = eINSTANCE.getPatternStatement_PatternType();

    /**
     * The meta object literal for the '{@link org.xtext.constraint.mydsl.myDsl.impl.PatternTypeImpl <em>Pattern Type</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.constraint.mydsl.myDsl.impl.PatternTypeImpl
     * @see org.xtext.constraint.mydsl.myDsl.impl.MyDslPackageImpl#getPatternType()
     * @generated
     */
    EClass PATTERN_TYPE = eINSTANCE.getPatternType();

    /**
     * The meta object literal for the '<em><b>First Event</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PATTERN_TYPE__FIRST_EVENT = eINSTANCE.getPatternType_FirstEvent();

    /**
     * The meta object literal for the '<em><b>Pattern Options</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PATTERN_TYPE__PATTERN_OPTIONS = eINSTANCE.getPatternType_PatternOptions();

    /**
     * The meta object literal for the '{@link org.xtext.constraint.mydsl.myDsl.impl.PatternOptionsImpl <em>Pattern Options</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.constraint.mydsl.myDsl.impl.PatternOptionsImpl
     * @see org.xtext.constraint.mydsl.myDsl.impl.MyDslPackageImpl#getPatternOptions()
     * @generated
     */
    EClass PATTERN_OPTIONS = eINSTANCE.getPatternOptions();

    /**
     * The meta object literal for the '<em><b>Occurence At Least</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PATTERN_OPTIONS__OCCURENCE_AT_LEAST = eINSTANCE.getPatternOptions_OccurenceAtLeast();

    /**
     * The meta object literal for the '<em><b>Occurence At Most</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PATTERN_OPTIONS__OCCURENCE_AT_MOST = eINSTANCE.getPatternOptions_OccurenceAtMost();

    /**
     * The meta object literal for the '<em><b>Occurence At Not Specific Time</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PATTERN_OPTIONS__OCCURENCE_AT_NOT_SPECIFIC_TIME = eINSTANCE.getPatternOptions_OccurenceAtNotSpecificTime();

    /**
     * The meta object literal for the '{@link org.xtext.constraint.mydsl.myDsl.impl.OccurenceAtTimeImpl <em>Occurence At Time</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.constraint.mydsl.myDsl.impl.OccurenceAtTimeImpl
     * @see org.xtext.constraint.mydsl.myDsl.impl.MyDslPackageImpl#getOccurenceAtTime()
     * @generated
     */
    EClass OCCURENCE_AT_TIME = eINSTANCE.getOccurenceAtTime();

    /**
     * The meta object literal for the '<em><b>Min Duration</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OCCURENCE_AT_TIME__MIN_DURATION = eINSTANCE.getOccurenceAtTime_MinDuration();

    /**
     * The meta object literal for the '<em><b>Max Duration</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OCCURENCE_AT_TIME__MAX_DURATION = eINSTANCE.getOccurenceAtTime_MaxDuration();

    /**
     * The meta object literal for the '{@link org.xtext.constraint.mydsl.myDsl.impl.OccurenceAtLeastImpl <em>Occurence At Least</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.constraint.mydsl.myDsl.impl.OccurenceAtLeastImpl
     * @see org.xtext.constraint.mydsl.myDsl.impl.MyDslPackageImpl#getOccurenceAtLeast()
     * @generated
     */
    EClass OCCURENCE_AT_LEAST = eINSTANCE.getOccurenceAtLeast();

    /**
     * The meta object literal for the '<em><b>Seceond Event</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OCCURENCE_AT_LEAST__SECEOND_EVENT = eINSTANCE.getOccurenceAtLeast_SeceondEvent();

    /**
     * The meta object literal for the '<em><b>Min Duration</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OCCURENCE_AT_LEAST__MIN_DURATION = eINSTANCE.getOccurenceAtLeast_MinDuration();

    /**
     * The meta object literal for the '{@link org.xtext.constraint.mydsl.myDsl.impl.OccurenceAtMostImpl <em>Occurence At Most</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.constraint.mydsl.myDsl.impl.OccurenceAtMostImpl
     * @see org.xtext.constraint.mydsl.myDsl.impl.MyDslPackageImpl#getOccurenceAtMost()
     * @generated
     */
    EClass OCCURENCE_AT_MOST = eINSTANCE.getOccurenceAtMost();

    /**
     * The meta object literal for the '<em><b>Seceond Event</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OCCURENCE_AT_MOST__SECEOND_EVENT = eINSTANCE.getOccurenceAtMost_SeceondEvent();

    /**
     * The meta object literal for the '<em><b>Max Duration</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OCCURENCE_AT_MOST__MAX_DURATION = eINSTANCE.getOccurenceAtMost_MaxDuration();

    /**
     * The meta object literal for the '{@link org.xtext.constraint.mydsl.myDsl.impl.OccurenceAtNotSpecificTimeImpl <em>Occurence At Not Specific Time</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.constraint.mydsl.myDsl.impl.OccurenceAtNotSpecificTimeImpl
     * @see org.xtext.constraint.mydsl.myDsl.impl.MyDslPackageImpl#getOccurenceAtNotSpecificTime()
     * @generated
     */
    EClass OCCURENCE_AT_NOT_SPECIFIC_TIME = eINSTANCE.getOccurenceAtNotSpecificTime();

    /**
     * The meta object literal for the '<em><b>Seceond Event</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OCCURENCE_AT_NOT_SPECIFIC_TIME__SECEOND_EVENT = eINSTANCE.getOccurenceAtNotSpecificTime_SeceondEvent();

    /**
     * The meta object literal for the '{@link org.xtext.constraint.mydsl.myDsl.impl.TimerImpl <em>Timer</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.constraint.mydsl.myDsl.impl.TimerImpl
     * @see org.xtext.constraint.mydsl.myDsl.impl.MyDslPackageImpl#getTimer()
     * @generated
     */
    EClass TIMER = eINSTANCE.getTimer();

    /**
     * The meta object literal for the '<em><b>Timer Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TIMER__TIMER_TYPE = eINSTANCE.getTimer_TimerType();

    /**
     * The meta object literal for the '<em><b>Time</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TIMER__TIME = eINSTANCE.getTimer_Time();

    /**
     * The meta object literal for the '<em><b>Time Unit</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TIMER__TIME_UNIT = eINSTANCE.getTimer_TimeUnit();

    /**
     * The meta object literal for the '{@link org.xtext.constraint.mydsl.myDsl.impl.MaxDurationImpl <em>Max Duration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.constraint.mydsl.myDsl.impl.MaxDurationImpl
     * @see org.xtext.constraint.mydsl.myDsl.impl.MyDslPackageImpl#getMaxDuration()
     * @generated
     */
    EClass MAX_DURATION = eINSTANCE.getMaxDuration();

    /**
     * The meta object literal for the '{@link org.xtext.constraint.mydsl.myDsl.impl.MinDurationImpl <em>Min Duration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.constraint.mydsl.myDsl.impl.MinDurationImpl
     * @see org.xtext.constraint.mydsl.myDsl.impl.MyDslPackageImpl#getMinDuration()
     * @generated
     */
    EClass MIN_DURATION = eINSTANCE.getMinDuration();

    /**
     * The meta object literal for the '{@link org.xtext.constraint.mydsl.myDsl.impl.TimeWindowImpl <em>Time Window</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.constraint.mydsl.myDsl.impl.TimeWindowImpl
     * @see org.xtext.constraint.mydsl.myDsl.impl.MyDslPackageImpl#getTimeWindow()
     * @generated
     */
    EClass TIME_WINDOW = eINSTANCE.getTimeWindow();

    /**
     * The meta object literal for the '<em><b>Time</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TIME_WINDOW__TIME = eINSTANCE.getTimeWindow_Time();

    /**
     * The meta object literal for the '<em><b>Time Unit</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TIME_WINDOW__TIME_UNIT = eINSTANCE.getTimeWindow_TimeUnit();

    /**
     * The meta object literal for the '{@link org.xtext.constraint.mydsl.myDsl.impl.ValueOptionsImpl <em>Value Options</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.constraint.mydsl.myDsl.impl.ValueOptionsImpl
     * @see org.xtext.constraint.mydsl.myDsl.impl.MyDslPackageImpl#getValueOptions()
     * @generated
     */
    EClass VALUE_OPTIONS = eINSTANCE.getValueOptions();

    /**
     * The meta object literal for the '<em><b>String Literal</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VALUE_OPTIONS__STRING_LITERAL = eINSTANCE.getValueOptions_StringLiteral();

    /**
     * The meta object literal for the '<em><b>Number Literal</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VALUE_OPTIONS__NUMBER_LITERAL = eINSTANCE.getValueOptions_NumberLiteral();

    /**
     * The meta object literal for the '<em><b>Text Literal</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VALUE_OPTIONS__TEXT_LITERAL = eINSTANCE.getValueOptions_TextLiteral();

    /**
     * The meta object literal for the '{@link org.xtext.constraint.mydsl.myDsl.impl.StringLiteralImpl <em>String Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.constraint.mydsl.myDsl.impl.StringLiteralImpl
     * @see org.xtext.constraint.mydsl.myDsl.impl.MyDslPackageImpl#getStringLiteral()
     * @generated
     */
    EClass STRING_LITERAL = eINSTANCE.getStringLiteral();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STRING_LITERAL__VALUE = eINSTANCE.getStringLiteral_Value();

    /**
     * The meta object literal for the '{@link org.xtext.constraint.mydsl.myDsl.impl.NumberLiteralImpl <em>Number Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.constraint.mydsl.myDsl.impl.NumberLiteralImpl
     * @see org.xtext.constraint.mydsl.myDsl.impl.MyDslPackageImpl#getNumberLiteral()
     * @generated
     */
    EClass NUMBER_LITERAL = eINSTANCE.getNumberLiteral();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NUMBER_LITERAL__VALUE = eINSTANCE.getNumberLiteral_Value();

    /**
     * The meta object literal for the '{@link org.xtext.constraint.mydsl.myDsl.impl.TextLiteralImpl <em>Text Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.constraint.mydsl.myDsl.impl.TextLiteralImpl
     * @see org.xtext.constraint.mydsl.myDsl.impl.MyDslPackageImpl#getTextLiteral()
     * @generated
     */
    EClass TEXT_LITERAL = eINSTANCE.getTextLiteral();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TEXT_LITERAL__VALUE = eINSTANCE.getTextLiteral_Value();

    /**
     * The meta object literal for the '{@link org.xtext.constraint.mydsl.myDsl.ComparisonOperator <em>Comparison Operator</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.constraint.mydsl.myDsl.ComparisonOperator
     * @see org.xtext.constraint.mydsl.myDsl.impl.MyDslPackageImpl#getComparisonOperator()
     * @generated
     */
    EEnum COMPARISON_OPERATOR = eINSTANCE.getComparisonOperator();

    /**
     * The meta object literal for the '{@link org.xtext.constraint.mydsl.myDsl.TimeUnit <em>Time Unit</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.constraint.mydsl.myDsl.TimeUnit
     * @see org.xtext.constraint.mydsl.myDsl.impl.MyDslPackageImpl#getTimeUnit()
     * @generated
     */
    EEnum TIME_UNIT = eINSTANCE.getTimeUnit();

    /**
     * The meta object literal for the '{@link org.xtext.constraint.mydsl.myDsl.GreedyQuantifiers <em>Greedy Quantifiers</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.constraint.mydsl.myDsl.GreedyQuantifiers
     * @see org.xtext.constraint.mydsl.myDsl.impl.MyDslPackageImpl#getGreedyQuantifiers()
     * @generated
     */
    EEnum GREEDY_QUANTIFIERS = eINSTANCE.getGreedyQuantifiers();

  }

} //MyDslPackage
