/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.constraint.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Occurence At Not Specific Time</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.constraint.mydsl.myDsl.OccurenceAtNotSpecificTime#getSeceondEvent <em>Seceond Event</em>}</li>
 * </ul>
 *
 * @see org.xtext.constraint.mydsl.myDsl.MyDslPackage#getOccurenceAtNotSpecificTime()
 * @model
 * @generated
 */
public interface OccurenceAtNotSpecificTime extends EObject
{
  /**
   * Returns the value of the '<em><b>Seceond Event</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Seceond Event</em>' reference.
   * @see #setSeceondEvent(InputStatement)
   * @see org.xtext.constraint.mydsl.myDsl.MyDslPackage#getOccurenceAtNotSpecificTime_SeceondEvent()
   * @model
   * @generated
   */
  InputStatement getSeceondEvent();

  /**
   * Sets the value of the '{@link org.xtext.constraint.mydsl.myDsl.OccurenceAtNotSpecificTime#getSeceondEvent <em>Seceond Event</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Seceond Event</em>' reference.
   * @see #getSeceondEvent()
   * @generated
   */
  void setSeceondEvent(InputStatement value);

} // OccurenceAtNotSpecificTime
