/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.constraint.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Occurence At Most</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.constraint.mydsl.myDsl.OccurenceAtMost#getSeceondEvent <em>Seceond Event</em>}</li>
 *   <li>{@link org.xtext.constraint.mydsl.myDsl.OccurenceAtMost#getMaxDuration <em>Max Duration</em>}</li>
 * </ul>
 *
 * @see org.xtext.constraint.mydsl.myDsl.MyDslPackage#getOccurenceAtMost()
 * @model
 * @generated
 */
public interface OccurenceAtMost extends EObject
{
  /**
   * Returns the value of the '<em><b>Seceond Event</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Seceond Event</em>' reference.
   * @see #setSeceondEvent(InputStatement)
   * @see org.xtext.constraint.mydsl.myDsl.MyDslPackage#getOccurenceAtMost_SeceondEvent()
   * @model
   * @generated
   */
  InputStatement getSeceondEvent();

  /**
   * Sets the value of the '{@link org.xtext.constraint.mydsl.myDsl.OccurenceAtMost#getSeceondEvent <em>Seceond Event</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Seceond Event</em>' reference.
   * @see #getSeceondEvent()
   * @generated
   */
  void setSeceondEvent(InputStatement value);

  /**
   * Returns the value of the '<em><b>Max Duration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Max Duration</em>' containment reference.
   * @see #setMaxDuration(MaxDuration)
   * @see org.xtext.constraint.mydsl.myDsl.MyDslPackage#getOccurenceAtMost_MaxDuration()
   * @model containment="true"
   * @generated
   */
  MaxDuration getMaxDuration();

  /**
   * Sets the value of the '{@link org.xtext.constraint.mydsl.myDsl.OccurenceAtMost#getMaxDuration <em>Max Duration</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Max Duration</em>' containment reference.
   * @see #getMaxDuration()
   * @generated
   */
  void setMaxDuration(MaxDuration value);

} // OccurenceAtMost
