/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.constraint.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Occurence At Time</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.constraint.mydsl.myDsl.OccurenceAtTime#getMinDuration <em>Min Duration</em>}</li>
 *   <li>{@link org.xtext.constraint.mydsl.myDsl.OccurenceAtTime#getMaxDuration <em>Max Duration</em>}</li>
 * </ul>
 *
 * @see org.xtext.constraint.mydsl.myDsl.MyDslPackage#getOccurenceAtTime()
 * @model
 * @generated
 */
public interface OccurenceAtTime extends EObject
{
  /**
   * Returns the value of the '<em><b>Min Duration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Min Duration</em>' containment reference.
   * @see #setMinDuration(MinDuration)
   * @see org.xtext.constraint.mydsl.myDsl.MyDslPackage#getOccurenceAtTime_MinDuration()
   * @model containment="true"
   * @generated
   */
  MinDuration getMinDuration();

  /**
   * Sets the value of the '{@link org.xtext.constraint.mydsl.myDsl.OccurenceAtTime#getMinDuration <em>Min Duration</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Min Duration</em>' containment reference.
   * @see #getMinDuration()
   * @generated
   */
  void setMinDuration(MinDuration value);

  /**
   * Returns the value of the '<em><b>Max Duration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Max Duration</em>' containment reference.
   * @see #setMaxDuration(MaxDuration)
   * @see org.xtext.constraint.mydsl.myDsl.MyDslPackage#getOccurenceAtTime_MaxDuration()
   * @model containment="true"
   * @generated
   */
  MaxDuration getMaxDuration();

  /**
   * Sets the value of the '{@link org.xtext.constraint.mydsl.myDsl.OccurenceAtTime#getMaxDuration <em>Max Duration</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Max Duration</em>' containment reference.
   * @see #getMaxDuration()
   * @generated
   */
  void setMaxDuration(MaxDuration value);

} // OccurenceAtTime
