/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.constraint.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Occurence At Least</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.constraint.mydsl.myDsl.OccurenceAtLeast#getSeceondEvent <em>Seceond Event</em>}</li>
 *   <li>{@link org.xtext.constraint.mydsl.myDsl.OccurenceAtLeast#getMinDuration <em>Min Duration</em>}</li>
 * </ul>
 *
 * @see org.xtext.constraint.mydsl.myDsl.MyDslPackage#getOccurenceAtLeast()
 * @model
 * @generated
 */
public interface OccurenceAtLeast extends EObject
{
  /**
   * Returns the value of the '<em><b>Seceond Event</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Seceond Event</em>' reference.
   * @see #setSeceondEvent(InputStatement)
   * @see org.xtext.constraint.mydsl.myDsl.MyDslPackage#getOccurenceAtLeast_SeceondEvent()
   * @model
   * @generated
   */
  InputStatement getSeceondEvent();

  /**
   * Sets the value of the '{@link org.xtext.constraint.mydsl.myDsl.OccurenceAtLeast#getSeceondEvent <em>Seceond Event</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Seceond Event</em>' reference.
   * @see #getSeceondEvent()
   * @generated
   */
  void setSeceondEvent(InputStatement value);

  /**
   * Returns the value of the '<em><b>Min Duration</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Min Duration</em>' containment reference.
   * @see #setMinDuration(MinDuration)
   * @see org.xtext.constraint.mydsl.myDsl.MyDslPackage#getOccurenceAtLeast_MinDuration()
   * @model containment="true"
   * @generated
   */
  MinDuration getMinDuration();

  /**
   * Sets the value of the '{@link org.xtext.constraint.mydsl.myDsl.OccurenceAtLeast#getMinDuration <em>Min Duration</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Min Duration</em>' containment reference.
   * @see #getMinDuration()
   * @generated
   */
  void setMinDuration(MinDuration value);

} // OccurenceAtLeast
