/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.constraint.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pattern Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.constraint.mydsl.myDsl.PatternType#getFirstEvent <em>First Event</em>}</li>
 *   <li>{@link org.xtext.constraint.mydsl.myDsl.PatternType#getPatternOptions <em>Pattern Options</em>}</li>
 * </ul>
 *
 * @see org.xtext.constraint.mydsl.myDsl.MyDslPackage#getPatternType()
 * @model
 * @generated
 */
public interface PatternType extends EObject
{
  /**
   * Returns the value of the '<em><b>First Event</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>First Event</em>' reference.
   * @see #setFirstEvent(InputStatement)
   * @see org.xtext.constraint.mydsl.myDsl.MyDslPackage#getPatternType_FirstEvent()
   * @model
   * @generated
   */
  InputStatement getFirstEvent();

  /**
   * Sets the value of the '{@link org.xtext.constraint.mydsl.myDsl.PatternType#getFirstEvent <em>First Event</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>First Event</em>' reference.
   * @see #getFirstEvent()
   * @generated
   */
  void setFirstEvent(InputStatement value);

  /**
   * Returns the value of the '<em><b>Pattern Options</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.constraint.mydsl.myDsl.PatternOptions}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pattern Options</em>' containment reference list.
   * @see org.xtext.constraint.mydsl.myDsl.MyDslPackage#getPatternType_PatternOptions()
   * @model containment="true"
   * @generated
   */
  EList<PatternOptions> getPatternOptions();

} // PatternType
