/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.constraint.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pattern Initialization</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.constraint.mydsl.myDsl.PatternInitialization#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.constraint.mydsl.myDsl.PatternInitialization#getTimeWindow <em>Time Window</em>}</li>
 *   <li>{@link org.xtext.constraint.mydsl.myDsl.PatternInitialization#getInputStatements <em>Input Statements</em>}</li>
 *   <li>{@link org.xtext.constraint.mydsl.myDsl.PatternInitialization#getPatternStatements <em>Pattern Statements</em>}</li>
 * </ul>
 *
 * @see org.xtext.constraint.mydsl.myDsl.MyDslPackage#getPatternInitialization()
 * @model
 * @generated
 */
public interface PatternInitialization extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.constraint.mydsl.myDsl.MyDslPackage#getPatternInitialization_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.constraint.mydsl.myDsl.PatternInitialization#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Time Window</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Time Window</em>' containment reference.
   * @see #setTimeWindow(TimeWindow)
   * @see org.xtext.constraint.mydsl.myDsl.MyDslPackage#getPatternInitialization_TimeWindow()
   * @model containment="true"
   * @generated
   */
  TimeWindow getTimeWindow();

  /**
   * Sets the value of the '{@link org.xtext.constraint.mydsl.myDsl.PatternInitialization#getTimeWindow <em>Time Window</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Time Window</em>' containment reference.
   * @see #getTimeWindow()
   * @generated
   */
  void setTimeWindow(TimeWindow value);

  /**
   * Returns the value of the '<em><b>Input Statements</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.constraint.mydsl.myDsl.InputStatement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Input Statements</em>' containment reference list.
   * @see org.xtext.constraint.mydsl.myDsl.MyDslPackage#getPatternInitialization_InputStatements()
   * @model containment="true"
   * @generated
   */
  EList<InputStatement> getInputStatements();

  /**
   * Returns the value of the '<em><b>Pattern Statements</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pattern Statements</em>' containment reference.
   * @see #setPatternStatements(PatternStatement)
   * @see org.xtext.constraint.mydsl.myDsl.MyDslPackage#getPatternInitialization_PatternStatements()
   * @model containment="true"
   * @generated
   */
  PatternStatement getPatternStatements();

  /**
   * Sets the value of the '{@link org.xtext.constraint.mydsl.myDsl.PatternInitialization#getPatternStatements <em>Pattern Statements</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pattern Statements</em>' containment reference.
   * @see #getPatternStatements()
   * @generated
   */
  void setPatternStatements(PatternStatement value);

} // PatternInitialization
