/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.constraint.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Pattern Options</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.constraint.mydsl.myDsl.PatternOptions#getOccurenceAtLeast <em>Occurence At Least</em>}</li>
 *   <li>{@link org.xtext.constraint.mydsl.myDsl.PatternOptions#getOccurenceAtMost <em>Occurence At Most</em>}</li>
 *   <li>{@link org.xtext.constraint.mydsl.myDsl.PatternOptions#getOccurenceAtNotSpecificTime <em>Occurence At Not Specific Time</em>}</li>
 * </ul>
 *
 * @see org.xtext.constraint.mydsl.myDsl.MyDslPackage#getPatternOptions()
 * @model
 * @generated
 */
public interface PatternOptions extends EObject
{
  /**
   * Returns the value of the '<em><b>Occurence At Least</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Occurence At Least</em>' containment reference.
   * @see #setOccurenceAtLeast(OccurenceAtLeast)
   * @see org.xtext.constraint.mydsl.myDsl.MyDslPackage#getPatternOptions_OccurenceAtLeast()
   * @model containment="true"
   * @generated
   */
  OccurenceAtLeast getOccurenceAtLeast();

  /**
   * Sets the value of the '{@link org.xtext.constraint.mydsl.myDsl.PatternOptions#getOccurenceAtLeast <em>Occurence At Least</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Occurence At Least</em>' containment reference.
   * @see #getOccurenceAtLeast()
   * @generated
   */
  void setOccurenceAtLeast(OccurenceAtLeast value);

  /**
   * Returns the value of the '<em><b>Occurence At Most</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Occurence At Most</em>' containment reference.
   * @see #setOccurenceAtMost(OccurenceAtMost)
   * @see org.xtext.constraint.mydsl.myDsl.MyDslPackage#getPatternOptions_OccurenceAtMost()
   * @model containment="true"
   * @generated
   */
  OccurenceAtMost getOccurenceAtMost();

  /**
   * Sets the value of the '{@link org.xtext.constraint.mydsl.myDsl.PatternOptions#getOccurenceAtMost <em>Occurence At Most</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Occurence At Most</em>' containment reference.
   * @see #getOccurenceAtMost()
   * @generated
   */
  void setOccurenceAtMost(OccurenceAtMost value);

  /**
   * Returns the value of the '<em><b>Occurence At Not Specific Time</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Occurence At Not Specific Time</em>' containment reference.
   * @see #setOccurenceAtNotSpecificTime(OccurenceAtNotSpecificTime)
   * @see org.xtext.constraint.mydsl.myDsl.MyDslPackage#getPatternOptions_OccurenceAtNotSpecificTime()
   * @model containment="true"
   * @generated
   */
  OccurenceAtNotSpecificTime getOccurenceAtNotSpecificTime();

  /**
   * Sets the value of the '{@link org.xtext.constraint.mydsl.myDsl.PatternOptions#getOccurenceAtNotSpecificTime <em>Occurence At Not Specific Time</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Occurence At Not Specific Time</em>' containment reference.
   * @see #getOccurenceAtNotSpecificTime()
   * @generated
   */
  void setOccurenceAtNotSpecificTime(OccurenceAtNotSpecificTime value);

} // PatternOptions
