/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.constraint.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Timer</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.constraint.mydsl.myDsl.Timer#getTimerType <em>Timer Type</em>}</li>
 *   <li>{@link org.xtext.constraint.mydsl.myDsl.Timer#getTime <em>Time</em>}</li>
 *   <li>{@link org.xtext.constraint.mydsl.myDsl.Timer#getTimeUnit <em>Time Unit</em>}</li>
 * </ul>
 *
 * @see org.xtext.constraint.mydsl.myDsl.MyDslPackage#getTimer()
 * @model
 * @generated
 */
public interface Timer extends EObject
{
  /**
   * Returns the value of the '<em><b>Timer Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Timer Type</em>' attribute.
   * @see #setTimerType(String)
   * @see org.xtext.constraint.mydsl.myDsl.MyDslPackage#getTimer_TimerType()
   * @model
   * @generated
   */
  String getTimerType();

  /**
   * Sets the value of the '{@link org.xtext.constraint.mydsl.myDsl.Timer#getTimerType <em>Timer Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Timer Type</em>' attribute.
   * @see #getTimerType()
   * @generated
   */
  void setTimerType(String value);

  /**
   * Returns the value of the '<em><b>Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Time</em>' attribute.
   * @see #setTime(int)
   * @see org.xtext.constraint.mydsl.myDsl.MyDslPackage#getTimer_Time()
   * @model
   * @generated
   */
  int getTime();

  /**
   * Sets the value of the '{@link org.xtext.constraint.mydsl.myDsl.Timer#getTime <em>Time</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Time</em>' attribute.
   * @see #getTime()
   * @generated
   */
  void setTime(int value);

  /**
   * Returns the value of the '<em><b>Time Unit</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.constraint.mydsl.myDsl.TimeUnit}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Time Unit</em>' attribute.
   * @see org.xtext.constraint.mydsl.myDsl.TimeUnit
   * @see #setTimeUnit(TimeUnit)
   * @see org.xtext.constraint.mydsl.myDsl.MyDslPackage#getTimer_TimeUnit()
   * @model
   * @generated
   */
  TimeUnit getTimeUnit();

  /**
   * Sets the value of the '{@link org.xtext.constraint.mydsl.myDsl.Timer#getTimeUnit <em>Time Unit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Time Unit</em>' attribute.
   * @see org.xtext.constraint.mydsl.myDsl.TimeUnit
   * @see #getTimeUnit()
   * @generated
   */
  void setTimeUnit(TimeUnit value);

} // Timer
