/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.constraint.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.constraint.mydsl.myDsl.ComplexPatternStatements;
import org.xtext.constraint.mydsl.myDsl.ComplexPatternType;
import org.xtext.constraint.mydsl.myDsl.MyDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Complex Pattern Statements</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.constraint.mydsl.myDsl.impl.ComplexPatternStatementsImpl#getComplexPatternType <em>Complex Pattern Type</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ComplexPatternStatementsImpl extends MinimalEObjectImpl.Container implements ComplexPatternStatements
{
  /**
   * The cached value of the '{@link #getComplexPatternType() <em>Complex Pattern Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getComplexPatternType()
   * @generated
   * @ordered
   */
  protected ComplexPatternType complexPatternType;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ComplexPatternStatementsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.COMPLEX_PATTERN_STATEMENTS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ComplexPatternType getComplexPatternType()
  {
    return complexPatternType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetComplexPatternType(ComplexPatternType newComplexPatternType, NotificationChain msgs)
  {
    ComplexPatternType oldComplexPatternType = complexPatternType;
    complexPatternType = newComplexPatternType;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.COMPLEX_PATTERN_STATEMENTS__COMPLEX_PATTERN_TYPE, oldComplexPatternType, newComplexPatternType);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setComplexPatternType(ComplexPatternType newComplexPatternType)
  {
    if (newComplexPatternType != complexPatternType)
    {
      NotificationChain msgs = null;
      if (complexPatternType != null)
        msgs = ((InternalEObject)complexPatternType).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.COMPLEX_PATTERN_STATEMENTS__COMPLEX_PATTERN_TYPE, null, msgs);
      if (newComplexPatternType != null)
        msgs = ((InternalEObject)newComplexPatternType).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.COMPLEX_PATTERN_STATEMENTS__COMPLEX_PATTERN_TYPE, null, msgs);
      msgs = basicSetComplexPatternType(newComplexPatternType, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.COMPLEX_PATTERN_STATEMENTS__COMPLEX_PATTERN_TYPE, newComplexPatternType, newComplexPatternType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.COMPLEX_PATTERN_STATEMENTS__COMPLEX_PATTERN_TYPE:
        return basicSetComplexPatternType(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.COMPLEX_PATTERN_STATEMENTS__COMPLEX_PATTERN_TYPE:
        return getComplexPatternType();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.COMPLEX_PATTERN_STATEMENTS__COMPLEX_PATTERN_TYPE:
        setComplexPatternType((ComplexPatternType)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.COMPLEX_PATTERN_STATEMENTS__COMPLEX_PATTERN_TYPE:
        setComplexPatternType((ComplexPatternType)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.COMPLEX_PATTERN_STATEMENTS__COMPLEX_PATTERN_TYPE:
        return complexPatternType != null;
    }
    return super.eIsSet(featureID);
  }

} //ComplexPatternStatementsImpl
