/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.constraint.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.constraint.mydsl.myDsl.MinDuration;
import org.xtext.constraint.mydsl.myDsl.MyDslPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Min Duration</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class MinDurationImpl extends TimerImpl implements MinDuration
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MinDurationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.MIN_DURATION;
  }

} //MinDurationImpl
