/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.constraint.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

import org.xtext.constraint.mydsl.myDsl.ComparisonOperator;
import org.xtext.constraint.mydsl.myDsl.ComplexInitialization;
import org.xtext.constraint.mydsl.myDsl.ComplexPatternOptions;
import org.xtext.constraint.mydsl.myDsl.ComplexPatternStatements;
import org.xtext.constraint.mydsl.myDsl.ComplexPatternType;
import org.xtext.constraint.mydsl.myDsl.GreedyQuantifiers;
import org.xtext.constraint.mydsl.myDsl.InputStatement;
import org.xtext.constraint.mydsl.myDsl.MaxDuration;
import org.xtext.constraint.mydsl.myDsl.MinDuration;
import org.xtext.constraint.mydsl.myDsl.MyDslFactory;
import org.xtext.constraint.mydsl.myDsl.MyDslPackage;
import org.xtext.constraint.mydsl.myDsl.NumberLiteral;
import org.xtext.constraint.mydsl.myDsl.OccurenceAtLeast;
import org.xtext.constraint.mydsl.myDsl.OccurenceAtMost;
import org.xtext.constraint.mydsl.myDsl.OccurenceAtNotSpecificTime;
import org.xtext.constraint.mydsl.myDsl.OccurenceAtTime;
import org.xtext.constraint.mydsl.myDsl.PatternInitialization;
import org.xtext.constraint.mydsl.myDsl.PatternModel;
import org.xtext.constraint.mydsl.myDsl.PatternOptions;
import org.xtext.constraint.mydsl.myDsl.PatternStatement;
import org.xtext.constraint.mydsl.myDsl.PatternType;
import org.xtext.constraint.mydsl.myDsl.QueryInitialization;
import org.xtext.constraint.mydsl.myDsl.StringLiteral;
import org.xtext.constraint.mydsl.myDsl.TextLiteral;
import org.xtext.constraint.mydsl.myDsl.TimeUnit;
import org.xtext.constraint.mydsl.myDsl.TimeWindow;
import org.xtext.constraint.mydsl.myDsl.Timer;
import org.xtext.constraint.mydsl.myDsl.ValueOptions;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class MyDslPackageImpl extends EPackageImpl implements MyDslPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass patternModelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass queryInitializationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass patternInitializationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass complexInitializationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass complexPatternStatementsEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass complexPatternTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass complexPatternOptionsEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass inputStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass patternStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass patternTypeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass patternOptionsEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass occurenceAtTimeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass occurenceAtLeastEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass occurenceAtMostEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass occurenceAtNotSpecificTimeEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass timerEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass maxDurationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass minDurationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass timeWindowEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass valueOptionsEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass stringLiteralEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass numberLiteralEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass textLiteralEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum comparisonOperatorEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum timeUnitEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum greedyQuantifiersEEnum = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see org.xtext.constraint.mydsl.myDsl.MyDslPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private MyDslPackageImpl()
  {
    super(eNS_URI, MyDslFactory.eINSTANCE);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link MyDslPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static MyDslPackage init()
  {
    if (isInited) return (MyDslPackage)EPackage.Registry.INSTANCE.getEPackage(MyDslPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredMyDslPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    MyDslPackageImpl theMyDslPackage = registeredMyDslPackage instanceof MyDslPackageImpl ? (MyDslPackageImpl)registeredMyDslPackage : new MyDslPackageImpl();

    isInited = true;

    // Create package meta-data objects
    theMyDslPackage.createPackageContents();

    // Initialize created meta-data
    theMyDslPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theMyDslPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(MyDslPackage.eNS_URI, theMyDslPackage);
    return theMyDslPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPatternModel()
  {
    return patternModelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPatternModel_Elements()
  {
    return (EReference)patternModelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getQueryInitialization()
  {
    return queryInitializationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getQueryInitialization_Name()
  {
    return (EAttribute)queryInitializationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getQueryInitialization_TimeWindow()
  {
    return (EReference)queryInitializationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getQueryInitialization_InputStatements()
  {
    return (EReference)queryInitializationEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPatternInitialization()
  {
    return patternInitializationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPatternInitialization_Name()
  {
    return (EAttribute)patternInitializationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPatternInitialization_TimeWindow()
  {
    return (EReference)patternInitializationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPatternInitialization_InputStatements()
  {
    return (EReference)patternInitializationEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPatternInitialization_PatternStatements()
  {
    return (EReference)patternInitializationEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getComplexInitialization()
  {
    return complexInitializationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getComplexInitialization_Name()
  {
    return (EAttribute)complexInitializationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComplexInitialization_TimeWindow()
  {
    return (EReference)complexInitializationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComplexInitialization_InputStatements()
  {
    return (EReference)complexInitializationEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComplexInitialization_ComplexPatternStatements()
  {
    return (EReference)complexInitializationEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getComplexPatternStatements()
  {
    return complexPatternStatementsEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComplexPatternStatements_ComplexPatternType()
  {
    return (EReference)complexPatternStatementsEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getComplexPatternType()
  {
    return complexPatternTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComplexPatternType_FirstEvent()
  {
    return (EReference)complexPatternTypeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getComplexPatternType_GreedyQuantifiers()
  {
    return (EAttribute)complexPatternTypeEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComplexPatternType_ComplexPatternOptions()
  {
    return (EReference)complexPatternTypeEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getComplexPatternOptions()
  {
    return complexPatternOptionsEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getComplexPatternOptions_SeceondEvent()
  {
    return (EReference)complexPatternOptionsEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getComplexPatternOptions_GreedyQuantifiers()
  {
    return (EAttribute)complexPatternOptionsEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getInputStatement()
  {
    return inputStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getInputStatement_Name()
  {
    return (EAttribute)inputStatementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getInputStatement_Property()
  {
    return (EAttribute)inputStatementEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getInputStatement_ComparisonOperator()
  {
    return (EAttribute)inputStatementEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getInputStatement_Value()
  {
    return (EReference)inputStatementEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPatternStatement()
  {
    return patternStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPatternStatement_PatternType()
  {
    return (EReference)patternStatementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPatternType()
  {
    return patternTypeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPatternType_FirstEvent()
  {
    return (EReference)patternTypeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPatternType_PatternOptions()
  {
    return (EReference)patternTypeEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPatternOptions()
  {
    return patternOptionsEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPatternOptions_OccurenceAtLeast()
  {
    return (EReference)patternOptionsEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPatternOptions_OccurenceAtMost()
  {
    return (EReference)patternOptionsEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getPatternOptions_OccurenceAtNotSpecificTime()
  {
    return (EReference)patternOptionsEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getOccurenceAtTime()
  {
    return occurenceAtTimeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getOccurenceAtTime_MinDuration()
  {
    return (EReference)occurenceAtTimeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getOccurenceAtTime_MaxDuration()
  {
    return (EReference)occurenceAtTimeEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getOccurenceAtLeast()
  {
    return occurenceAtLeastEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getOccurenceAtLeast_SeceondEvent()
  {
    return (EReference)occurenceAtLeastEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getOccurenceAtLeast_MinDuration()
  {
    return (EReference)occurenceAtLeastEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getOccurenceAtMost()
  {
    return occurenceAtMostEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getOccurenceAtMost_SeceondEvent()
  {
    return (EReference)occurenceAtMostEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getOccurenceAtMost_MaxDuration()
  {
    return (EReference)occurenceAtMostEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getOccurenceAtNotSpecificTime()
  {
    return occurenceAtNotSpecificTimeEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getOccurenceAtNotSpecificTime_SeceondEvent()
  {
    return (EReference)occurenceAtNotSpecificTimeEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getTimer()
  {
    return timerEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getTimer_TimerType()
  {
    return (EAttribute)timerEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getTimer_Time()
  {
    return (EAttribute)timerEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getTimer_TimeUnit()
  {
    return (EAttribute)timerEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMaxDuration()
  {
    return maxDurationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMinDuration()
  {
    return minDurationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getTimeWindow()
  {
    return timeWindowEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getTimeWindow_Time()
  {
    return (EAttribute)timeWindowEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getTimeWindow_TimeUnit()
  {
    return (EAttribute)timeWindowEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getValueOptions()
  {
    return valueOptionsEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getValueOptions_StringLiteral()
  {
    return (EReference)valueOptionsEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getValueOptions_NumberLiteral()
  {
    return (EReference)valueOptionsEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getValueOptions_TextLiteral()
  {
    return (EReference)valueOptionsEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getStringLiteral()
  {
    return stringLiteralEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getStringLiteral_Value()
  {
    return (EAttribute)stringLiteralEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getNumberLiteral()
  {
    return numberLiteralEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getNumberLiteral_Value()
  {
    return (EAttribute)numberLiteralEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getTextLiteral()
  {
    return textLiteralEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getTextLiteral_Value()
  {
    return (EAttribute)textLiteralEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getComparisonOperator()
  {
    return comparisonOperatorEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getTimeUnit()
  {
    return timeUnitEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getGreedyQuantifiers()
  {
    return greedyQuantifiersEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MyDslFactory getMyDslFactory()
  {
    return (MyDslFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    patternModelEClass = createEClass(PATTERN_MODEL);
    createEReference(patternModelEClass, PATTERN_MODEL__ELEMENTS);

    queryInitializationEClass = createEClass(QUERY_INITIALIZATION);
    createEAttribute(queryInitializationEClass, QUERY_INITIALIZATION__NAME);
    createEReference(queryInitializationEClass, QUERY_INITIALIZATION__TIME_WINDOW);
    createEReference(queryInitializationEClass, QUERY_INITIALIZATION__INPUT_STATEMENTS);

    patternInitializationEClass = createEClass(PATTERN_INITIALIZATION);
    createEAttribute(patternInitializationEClass, PATTERN_INITIALIZATION__NAME);
    createEReference(patternInitializationEClass, PATTERN_INITIALIZATION__TIME_WINDOW);
    createEReference(patternInitializationEClass, PATTERN_INITIALIZATION__INPUT_STATEMENTS);
    createEReference(patternInitializationEClass, PATTERN_INITIALIZATION__PATTERN_STATEMENTS);

    complexInitializationEClass = createEClass(COMPLEX_INITIALIZATION);
    createEAttribute(complexInitializationEClass, COMPLEX_INITIALIZATION__NAME);
    createEReference(complexInitializationEClass, COMPLEX_INITIALIZATION__TIME_WINDOW);
    createEReference(complexInitializationEClass, COMPLEX_INITIALIZATION__INPUT_STATEMENTS);
    createEReference(complexInitializationEClass, COMPLEX_INITIALIZATION__COMPLEX_PATTERN_STATEMENTS);

    complexPatternStatementsEClass = createEClass(COMPLEX_PATTERN_STATEMENTS);
    createEReference(complexPatternStatementsEClass, COMPLEX_PATTERN_STATEMENTS__COMPLEX_PATTERN_TYPE);

    complexPatternTypeEClass = createEClass(COMPLEX_PATTERN_TYPE);
    createEReference(complexPatternTypeEClass, COMPLEX_PATTERN_TYPE__FIRST_EVENT);
    createEAttribute(complexPatternTypeEClass, COMPLEX_PATTERN_TYPE__GREEDY_QUANTIFIERS);
    createEReference(complexPatternTypeEClass, COMPLEX_PATTERN_TYPE__COMPLEX_PATTERN_OPTIONS);

    complexPatternOptionsEClass = createEClass(COMPLEX_PATTERN_OPTIONS);
    createEReference(complexPatternOptionsEClass, COMPLEX_PATTERN_OPTIONS__SECEOND_EVENT);
    createEAttribute(complexPatternOptionsEClass, COMPLEX_PATTERN_OPTIONS__GREEDY_QUANTIFIERS);

    inputStatementEClass = createEClass(INPUT_STATEMENT);
    createEAttribute(inputStatementEClass, INPUT_STATEMENT__NAME);
    createEAttribute(inputStatementEClass, INPUT_STATEMENT__PROPERTY);
    createEAttribute(inputStatementEClass, INPUT_STATEMENT__COMPARISON_OPERATOR);
    createEReference(inputStatementEClass, INPUT_STATEMENT__VALUE);

    patternStatementEClass = createEClass(PATTERN_STATEMENT);
    createEReference(patternStatementEClass, PATTERN_STATEMENT__PATTERN_TYPE);

    patternTypeEClass = createEClass(PATTERN_TYPE);
    createEReference(patternTypeEClass, PATTERN_TYPE__FIRST_EVENT);
    createEReference(patternTypeEClass, PATTERN_TYPE__PATTERN_OPTIONS);

    patternOptionsEClass = createEClass(PATTERN_OPTIONS);
    createEReference(patternOptionsEClass, PATTERN_OPTIONS__OCCURENCE_AT_LEAST);
    createEReference(patternOptionsEClass, PATTERN_OPTIONS__OCCURENCE_AT_MOST);
    createEReference(patternOptionsEClass, PATTERN_OPTIONS__OCCURENCE_AT_NOT_SPECIFIC_TIME);

    occurenceAtTimeEClass = createEClass(OCCURENCE_AT_TIME);
    createEReference(occurenceAtTimeEClass, OCCURENCE_AT_TIME__MIN_DURATION);
    createEReference(occurenceAtTimeEClass, OCCURENCE_AT_TIME__MAX_DURATION);

    occurenceAtLeastEClass = createEClass(OCCURENCE_AT_LEAST);
    createEReference(occurenceAtLeastEClass, OCCURENCE_AT_LEAST__SECEOND_EVENT);
    createEReference(occurenceAtLeastEClass, OCCURENCE_AT_LEAST__MIN_DURATION);

    occurenceAtMostEClass = createEClass(OCCURENCE_AT_MOST);
    createEReference(occurenceAtMostEClass, OCCURENCE_AT_MOST__SECEOND_EVENT);
    createEReference(occurenceAtMostEClass, OCCURENCE_AT_MOST__MAX_DURATION);

    occurenceAtNotSpecificTimeEClass = createEClass(OCCURENCE_AT_NOT_SPECIFIC_TIME);
    createEReference(occurenceAtNotSpecificTimeEClass, OCCURENCE_AT_NOT_SPECIFIC_TIME__SECEOND_EVENT);

    timerEClass = createEClass(TIMER);
    createEAttribute(timerEClass, TIMER__TIMER_TYPE);
    createEAttribute(timerEClass, TIMER__TIME);
    createEAttribute(timerEClass, TIMER__TIME_UNIT);

    maxDurationEClass = createEClass(MAX_DURATION);

    minDurationEClass = createEClass(MIN_DURATION);

    timeWindowEClass = createEClass(TIME_WINDOW);
    createEAttribute(timeWindowEClass, TIME_WINDOW__TIME);
    createEAttribute(timeWindowEClass, TIME_WINDOW__TIME_UNIT);

    valueOptionsEClass = createEClass(VALUE_OPTIONS);
    createEReference(valueOptionsEClass, VALUE_OPTIONS__STRING_LITERAL);
    createEReference(valueOptionsEClass, VALUE_OPTIONS__NUMBER_LITERAL);
    createEReference(valueOptionsEClass, VALUE_OPTIONS__TEXT_LITERAL);

    stringLiteralEClass = createEClass(STRING_LITERAL);
    createEAttribute(stringLiteralEClass, STRING_LITERAL__VALUE);

    numberLiteralEClass = createEClass(NUMBER_LITERAL);
    createEAttribute(numberLiteralEClass, NUMBER_LITERAL__VALUE);

    textLiteralEClass = createEClass(TEXT_LITERAL);
    createEAttribute(textLiteralEClass, TEXT_LITERAL__VALUE);

    // Create enums
    comparisonOperatorEEnum = createEEnum(COMPARISON_OPERATOR);
    timeUnitEEnum = createEEnum(TIME_UNIT);
    greedyQuantifiersEEnum = createEEnum(GREEDY_QUANTIFIERS);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    maxDurationEClass.getESuperTypes().add(this.getTimer());
    minDurationEClass.getESuperTypes().add(this.getTimer());

    // Initialize classes and features; add operations and parameters
    initEClass(patternModelEClass, PatternModel.class, "PatternModel", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getPatternModel_Elements(), ecorePackage.getEObject(), null, "elements", null, 0, 1, PatternModel.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(queryInitializationEClass, QueryInitialization.class, "QueryInitialization", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getQueryInitialization_Name(), ecorePackage.getEString(), "name", null, 0, 1, QueryInitialization.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getQueryInitialization_TimeWindow(), this.getTimeWindow(), null, "timeWindow", null, 0, 1, QueryInitialization.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getQueryInitialization_InputStatements(), this.getInputStatement(), null, "inputStatements", null, 0, 1, QueryInitialization.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(patternInitializationEClass, PatternInitialization.class, "PatternInitialization", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getPatternInitialization_Name(), ecorePackage.getEString(), "name", null, 0, 1, PatternInitialization.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getPatternInitialization_TimeWindow(), this.getTimeWindow(), null, "timeWindow", null, 0, 1, PatternInitialization.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getPatternInitialization_InputStatements(), this.getInputStatement(), null, "inputStatements", null, 0, -1, PatternInitialization.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getPatternInitialization_PatternStatements(), this.getPatternStatement(), null, "patternStatements", null, 0, 1, PatternInitialization.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(complexInitializationEClass, ComplexInitialization.class, "ComplexInitialization", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getComplexInitialization_Name(), ecorePackage.getEString(), "name", null, 0, 1, ComplexInitialization.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getComplexInitialization_TimeWindow(), this.getTimeWindow(), null, "timeWindow", null, 0, 1, ComplexInitialization.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getComplexInitialization_InputStatements(), this.getInputStatement(), null, "inputStatements", null, 0, -1, ComplexInitialization.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getComplexInitialization_ComplexPatternStatements(), this.getComplexPatternStatements(), null, "complexPatternStatements", null, 0, 1, ComplexInitialization.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(complexPatternStatementsEClass, ComplexPatternStatements.class, "ComplexPatternStatements", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getComplexPatternStatements_ComplexPatternType(), this.getComplexPatternType(), null, "complexPatternType", null, 0, 1, ComplexPatternStatements.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(complexPatternTypeEClass, ComplexPatternType.class, "ComplexPatternType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getComplexPatternType_FirstEvent(), this.getInputStatement(), null, "firstEvent", null, 0, 1, ComplexPatternType.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getComplexPatternType_GreedyQuantifiers(), this.getGreedyQuantifiers(), "greedyQuantifiers", null, 0, 1, ComplexPatternType.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getComplexPatternType_ComplexPatternOptions(), this.getComplexPatternOptions(), null, "complexPatternOptions", null, 0, -1, ComplexPatternType.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(complexPatternOptionsEClass, ComplexPatternOptions.class, "ComplexPatternOptions", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getComplexPatternOptions_SeceondEvent(), this.getInputStatement(), null, "seceondEvent", null, 0, 1, ComplexPatternOptions.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getComplexPatternOptions_GreedyQuantifiers(), this.getGreedyQuantifiers(), "greedyQuantifiers", null, 0, 1, ComplexPatternOptions.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(inputStatementEClass, InputStatement.class, "InputStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getInputStatement_Name(), ecorePackage.getEString(), "name", null, 0, 1, InputStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getInputStatement_Property(), ecorePackage.getEString(), "Property", null, 0, 1, InputStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getInputStatement_ComparisonOperator(), this.getComparisonOperator(), "comparisonOperator", null, 0, 1, InputStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getInputStatement_Value(), this.getValueOptions(), null, "value", null, 0, 1, InputStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(patternStatementEClass, PatternStatement.class, "PatternStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getPatternStatement_PatternType(), this.getPatternType(), null, "patternType", null, 0, 1, PatternStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(patternTypeEClass, PatternType.class, "PatternType", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getPatternType_FirstEvent(), this.getInputStatement(), null, "firstEvent", null, 0, 1, PatternType.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getPatternType_PatternOptions(), this.getPatternOptions(), null, "patternOptions", null, 0, -1, PatternType.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(patternOptionsEClass, PatternOptions.class, "PatternOptions", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getPatternOptions_OccurenceAtLeast(), this.getOccurenceAtLeast(), null, "occurenceAtLeast", null, 0, 1, PatternOptions.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getPatternOptions_OccurenceAtMost(), this.getOccurenceAtMost(), null, "occurenceAtMost", null, 0, 1, PatternOptions.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getPatternOptions_OccurenceAtNotSpecificTime(), this.getOccurenceAtNotSpecificTime(), null, "occurenceAtNotSpecificTime", null, 0, 1, PatternOptions.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(occurenceAtTimeEClass, OccurenceAtTime.class, "OccurenceAtTime", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getOccurenceAtTime_MinDuration(), this.getMinDuration(), null, "minDuration", null, 0, 1, OccurenceAtTime.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getOccurenceAtTime_MaxDuration(), this.getMaxDuration(), null, "maxDuration", null, 0, 1, OccurenceAtTime.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(occurenceAtLeastEClass, OccurenceAtLeast.class, "OccurenceAtLeast", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getOccurenceAtLeast_SeceondEvent(), this.getInputStatement(), null, "seceondEvent", null, 0, 1, OccurenceAtLeast.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getOccurenceAtLeast_MinDuration(), this.getMinDuration(), null, "minDuration", null, 0, 1, OccurenceAtLeast.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(occurenceAtMostEClass, OccurenceAtMost.class, "OccurenceAtMost", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getOccurenceAtMost_SeceondEvent(), this.getInputStatement(), null, "seceondEvent", null, 0, 1, OccurenceAtMost.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getOccurenceAtMost_MaxDuration(), this.getMaxDuration(), null, "maxDuration", null, 0, 1, OccurenceAtMost.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(occurenceAtNotSpecificTimeEClass, OccurenceAtNotSpecificTime.class, "OccurenceAtNotSpecificTime", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getOccurenceAtNotSpecificTime_SeceondEvent(), this.getInputStatement(), null, "seceondEvent", null, 0, 1, OccurenceAtNotSpecificTime.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(timerEClass, Timer.class, "Timer", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getTimer_TimerType(), ecorePackage.getEString(), "timerType", null, 0, 1, Timer.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getTimer_Time(), ecorePackage.getEInt(), "time", null, 0, 1, Timer.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getTimer_TimeUnit(), this.getTimeUnit(), "timeUnit", null, 0, 1, Timer.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(maxDurationEClass, MaxDuration.class, "MaxDuration", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(minDurationEClass, MinDuration.class, "MinDuration", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(timeWindowEClass, TimeWindow.class, "TimeWindow", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getTimeWindow_Time(), ecorePackage.getEInt(), "time", null, 0, 1, TimeWindow.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getTimeWindow_TimeUnit(), this.getTimeUnit(), "timeUnit", null, 0, 1, TimeWindow.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(valueOptionsEClass, ValueOptions.class, "ValueOptions", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getValueOptions_StringLiteral(), this.getStringLiteral(), null, "stringLiteral", null, 0, 1, ValueOptions.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getValueOptions_NumberLiteral(), this.getNumberLiteral(), null, "numberLiteral", null, 0, 1, ValueOptions.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getValueOptions_TextLiteral(), this.getTextLiteral(), null, "textLiteral", null, 0, 1, ValueOptions.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(stringLiteralEClass, StringLiteral.class, "StringLiteral", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getStringLiteral_Value(), ecorePackage.getEString(), "value", null, 0, 1, StringLiteral.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(numberLiteralEClass, NumberLiteral.class, "NumberLiteral", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getNumberLiteral_Value(), ecorePackage.getEInt(), "value", null, 0, 1, NumberLiteral.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(textLiteralEClass, TextLiteral.class, "TextLiteral", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getTextLiteral_Value(), ecorePackage.getEString(), "value", null, 0, 1, TextLiteral.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Initialize enums and add enum literals
    initEEnum(comparisonOperatorEEnum, ComparisonOperator.class, "ComparisonOperator");
    addEEnumLiteral(comparisonOperatorEEnum, ComparisonOperator.EQUAL);
    addEEnumLiteral(comparisonOperatorEEnum, ComparisonOperator.NOT_EQUAL);
    addEEnumLiteral(comparisonOperatorEEnum, ComparisonOperator.BIGGER_THAN);
    addEEnumLiteral(comparisonOperatorEEnum, ComparisonOperator.LESS_THAN);
    addEEnumLiteral(comparisonOperatorEEnum, ComparisonOperator.LESS_THAN_OR_EQUAL);
    addEEnumLiteral(comparisonOperatorEEnum, ComparisonOperator.BIGGER_THAN_OR_EQUAL);

    initEEnum(timeUnitEEnum, TimeUnit.class, "TimeUnit");
    addEEnumLiteral(timeUnitEEnum, TimeUnit.MICRO_SECONDS);
    addEEnumLiteral(timeUnitEEnum, TimeUnit.MILLI_SECONDS);
    addEEnumLiteral(timeUnitEEnum, TimeUnit.SECONDS);
    addEEnumLiteral(timeUnitEEnum, TimeUnit.MINUTE);
    addEEnumLiteral(timeUnitEEnum, TimeUnit.HOUR);
    addEEnumLiteral(timeUnitEEnum, TimeUnit.DAY);

    initEEnum(greedyQuantifiersEEnum, GreedyQuantifiers.class, "GreedyQuantifiers");
    addEEnumLiteral(greedyQuantifiersEEnum, GreedyQuantifiers.ONCE);
    addEEnumLiteral(greedyQuantifiersEEnum, GreedyQuantifiers.ZERO_OR_MORE);
    addEEnumLiteral(greedyQuantifiersEEnum, GreedyQuantifiers.ONE_OR_MORE);
    addEEnumLiteral(greedyQuantifiersEEnum, GreedyQuantifiers.ZERO_OR_ONE);

    // Create resource
    createResource(eNS_URI);
  }

} //MyDslPackageImpl
