/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.constraint.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.constraint.mydsl.myDsl.InputStatement;
import org.xtext.constraint.mydsl.myDsl.MyDslPackage;
import org.xtext.constraint.mydsl.myDsl.OccurenceAtNotSpecificTime;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Occurence At Not Specific Time</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.constraint.mydsl.myDsl.impl.OccurenceAtNotSpecificTimeImpl#getSeceondEvent <em>Seceond Event</em>}</li>
 * </ul>
 *
 * @generated
 */
public class OccurenceAtNotSpecificTimeImpl extends MinimalEObjectImpl.Container implements OccurenceAtNotSpecificTime
{
  /**
   * The cached value of the '{@link #getSeceondEvent() <em>Seceond Event</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSeceondEvent()
   * @generated
   * @ordered
   */
  protected InputStatement seceondEvent;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected OccurenceAtNotSpecificTimeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.OCCURENCE_AT_NOT_SPECIFIC_TIME;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public InputStatement getSeceondEvent()
  {
    if (seceondEvent != null && seceondEvent.eIsProxy())
    {
      InternalEObject oldSeceondEvent = (InternalEObject)seceondEvent;
      seceondEvent = (InputStatement)eResolveProxy(oldSeceondEvent);
      if (seceondEvent != oldSeceondEvent)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, MyDslPackage.OCCURENCE_AT_NOT_SPECIFIC_TIME__SECEOND_EVENT, oldSeceondEvent, seceondEvent));
      }
    }
    return seceondEvent;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public InputStatement basicGetSeceondEvent()
  {
    return seceondEvent;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSeceondEvent(InputStatement newSeceondEvent)
  {
    InputStatement oldSeceondEvent = seceondEvent;
    seceondEvent = newSeceondEvent;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.OCCURENCE_AT_NOT_SPECIFIC_TIME__SECEOND_EVENT, oldSeceondEvent, seceondEvent));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.OCCURENCE_AT_NOT_SPECIFIC_TIME__SECEOND_EVENT:
        if (resolve) return getSeceondEvent();
        return basicGetSeceondEvent();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.OCCURENCE_AT_NOT_SPECIFIC_TIME__SECEOND_EVENT:
        setSeceondEvent((InputStatement)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.OCCURENCE_AT_NOT_SPECIFIC_TIME__SECEOND_EVENT:
        setSeceondEvent((InputStatement)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.OCCURENCE_AT_NOT_SPECIFIC_TIME__SECEOND_EVENT:
        return seceondEvent != null;
    }
    return super.eIsSet(featureID);
  }

} //OccurenceAtNotSpecificTimeImpl
