/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.constraint.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.constraint.mydsl.myDsl.MyDslPackage;
import org.xtext.constraint.mydsl.myDsl.PatternStatement;
import org.xtext.constraint.mydsl.myDsl.PatternType;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Pattern Statement</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.constraint.mydsl.myDsl.impl.PatternStatementImpl#getPatternType <em>Pattern Type</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PatternStatementImpl extends MinimalEObjectImpl.Container implements PatternStatement
{
  /**
   * The cached value of the '{@link #getPatternType() <em>Pattern Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPatternType()
   * @generated
   * @ordered
   */
  protected PatternType patternType;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PatternStatementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.PATTERN_STATEMENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public PatternType getPatternType()
  {
    return patternType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPatternType(PatternType newPatternType, NotificationChain msgs)
  {
    PatternType oldPatternType = patternType;
    patternType = newPatternType;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.PATTERN_STATEMENT__PATTERN_TYPE, oldPatternType, newPatternType);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setPatternType(PatternType newPatternType)
  {
    if (newPatternType != patternType)
    {
      NotificationChain msgs = null;
      if (patternType != null)
        msgs = ((InternalEObject)patternType).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.PATTERN_STATEMENT__PATTERN_TYPE, null, msgs);
      if (newPatternType != null)
        msgs = ((InternalEObject)newPatternType).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.PATTERN_STATEMENT__PATTERN_TYPE, null, msgs);
      msgs = basicSetPatternType(newPatternType, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.PATTERN_STATEMENT__PATTERN_TYPE, newPatternType, newPatternType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.PATTERN_STATEMENT__PATTERN_TYPE:
        return basicSetPatternType(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.PATTERN_STATEMENT__PATTERN_TYPE:
        return getPatternType();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.PATTERN_STATEMENT__PATTERN_TYPE:
        setPatternType((PatternType)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.PATTERN_STATEMENT__PATTERN_TYPE:
        setPatternType((PatternType)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.PATTERN_STATEMENT__PATTERN_TYPE:
        return patternType != null;
    }
    return super.eIsSet(featureID);
  }

} //PatternStatementImpl
