/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.constraint.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.constraint.mydsl.myDsl.InputStatement;
import org.xtext.constraint.mydsl.myDsl.MyDslPackage;
import org.xtext.constraint.mydsl.myDsl.QueryInitialization;
import org.xtext.constraint.mydsl.myDsl.TimeWindow;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Query Initialization</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.constraint.mydsl.myDsl.impl.QueryInitializationImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.constraint.mydsl.myDsl.impl.QueryInitializationImpl#getTimeWindow <em>Time Window</em>}</li>
 *   <li>{@link org.xtext.constraint.mydsl.myDsl.impl.QueryInitializationImpl#getInputStatements <em>Input Statements</em>}</li>
 * </ul>
 *
 * @generated
 */
public class QueryInitializationImpl extends MinimalEObjectImpl.Container implements QueryInitialization
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getTimeWindow() <em>Time Window</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTimeWindow()
   * @generated
   * @ordered
   */
  protected TimeWindow timeWindow;

  /**
   * The cached value of the '{@link #getInputStatements() <em>Input Statements</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getInputStatements()
   * @generated
   * @ordered
   */
  protected InputStatement inputStatements;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected QueryInitializationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.QUERY_INITIALIZATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.QUERY_INITIALIZATION__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TimeWindow getTimeWindow()
  {
    return timeWindow;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTimeWindow(TimeWindow newTimeWindow, NotificationChain msgs)
  {
    TimeWindow oldTimeWindow = timeWindow;
    timeWindow = newTimeWindow;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.QUERY_INITIALIZATION__TIME_WINDOW, oldTimeWindow, newTimeWindow);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTimeWindow(TimeWindow newTimeWindow)
  {
    if (newTimeWindow != timeWindow)
    {
      NotificationChain msgs = null;
      if (timeWindow != null)
        msgs = ((InternalEObject)timeWindow).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.QUERY_INITIALIZATION__TIME_WINDOW, null, msgs);
      if (newTimeWindow != null)
        msgs = ((InternalEObject)newTimeWindow).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.QUERY_INITIALIZATION__TIME_WINDOW, null, msgs);
      msgs = basicSetTimeWindow(newTimeWindow, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.QUERY_INITIALIZATION__TIME_WINDOW, newTimeWindow, newTimeWindow));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public InputStatement getInputStatements()
  {
    return inputStatements;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetInputStatements(InputStatement newInputStatements, NotificationChain msgs)
  {
    InputStatement oldInputStatements = inputStatements;
    inputStatements = newInputStatements;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.QUERY_INITIALIZATION__INPUT_STATEMENTS, oldInputStatements, newInputStatements);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setInputStatements(InputStatement newInputStatements)
  {
    if (newInputStatements != inputStatements)
    {
      NotificationChain msgs = null;
      if (inputStatements != null)
        msgs = ((InternalEObject)inputStatements).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.QUERY_INITIALIZATION__INPUT_STATEMENTS, null, msgs);
      if (newInputStatements != null)
        msgs = ((InternalEObject)newInputStatements).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.QUERY_INITIALIZATION__INPUT_STATEMENTS, null, msgs);
      msgs = basicSetInputStatements(newInputStatements, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.QUERY_INITIALIZATION__INPUT_STATEMENTS, newInputStatements, newInputStatements));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.QUERY_INITIALIZATION__TIME_WINDOW:
        return basicSetTimeWindow(null, msgs);
      case MyDslPackage.QUERY_INITIALIZATION__INPUT_STATEMENTS:
        return basicSetInputStatements(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.QUERY_INITIALIZATION__NAME:
        return getName();
      case MyDslPackage.QUERY_INITIALIZATION__TIME_WINDOW:
        return getTimeWindow();
      case MyDslPackage.QUERY_INITIALIZATION__INPUT_STATEMENTS:
        return getInputStatements();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.QUERY_INITIALIZATION__NAME:
        setName((String)newValue);
        return;
      case MyDslPackage.QUERY_INITIALIZATION__TIME_WINDOW:
        setTimeWindow((TimeWindow)newValue);
        return;
      case MyDslPackage.QUERY_INITIALIZATION__INPUT_STATEMENTS:
        setInputStatements((InputStatement)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.QUERY_INITIALIZATION__NAME:
        setName(NAME_EDEFAULT);
        return;
      case MyDslPackage.QUERY_INITIALIZATION__TIME_WINDOW:
        setTimeWindow((TimeWindow)null);
        return;
      case MyDslPackage.QUERY_INITIALIZATION__INPUT_STATEMENTS:
        setInputStatements((InputStatement)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.QUERY_INITIALIZATION__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case MyDslPackage.QUERY_INITIALIZATION__TIME_WINDOW:
        return timeWindow != null;
      case MyDslPackage.QUERY_INITIALIZATION__INPUT_STATEMENTS:
        return inputStatements != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //QueryInitializationImpl
