/**
 * generated by Xtext 2.26.0-SNAPSHOT
 */
package org.xtext.constraint.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.constraint.mydsl.myDsl.MyDslPackage;
import org.xtext.constraint.mydsl.myDsl.NumberLiteral;
import org.xtext.constraint.mydsl.myDsl.StringLiteral;
import org.xtext.constraint.mydsl.myDsl.TextLiteral;
import org.xtext.constraint.mydsl.myDsl.ValueOptions;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Value Options</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.constraint.mydsl.myDsl.impl.ValueOptionsImpl#getStringLiteral <em>String Literal</em>}</li>
 *   <li>{@link org.xtext.constraint.mydsl.myDsl.impl.ValueOptionsImpl#getNumberLiteral <em>Number Literal</em>}</li>
 *   <li>{@link org.xtext.constraint.mydsl.myDsl.impl.ValueOptionsImpl#getTextLiteral <em>Text Literal</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ValueOptionsImpl extends MinimalEObjectImpl.Container implements ValueOptions
{
  /**
   * The cached value of the '{@link #getStringLiteral() <em>String Literal</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStringLiteral()
   * @generated
   * @ordered
   */
  protected StringLiteral stringLiteral;

  /**
   * The cached value of the '{@link #getNumberLiteral() <em>Number Literal</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNumberLiteral()
   * @generated
   * @ordered
   */
  protected NumberLiteral numberLiteral;

  /**
   * The cached value of the '{@link #getTextLiteral() <em>Text Literal</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTextLiteral()
   * @generated
   * @ordered
   */
  protected TextLiteral textLiteral;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ValueOptionsImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.VALUE_OPTIONS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public StringLiteral getStringLiteral()
  {
    return stringLiteral;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetStringLiteral(StringLiteral newStringLiteral, NotificationChain msgs)
  {
    StringLiteral oldStringLiteral = stringLiteral;
    stringLiteral = newStringLiteral;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.VALUE_OPTIONS__STRING_LITERAL, oldStringLiteral, newStringLiteral);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setStringLiteral(StringLiteral newStringLiteral)
  {
    if (newStringLiteral != stringLiteral)
    {
      NotificationChain msgs = null;
      if (stringLiteral != null)
        msgs = ((InternalEObject)stringLiteral).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.VALUE_OPTIONS__STRING_LITERAL, null, msgs);
      if (newStringLiteral != null)
        msgs = ((InternalEObject)newStringLiteral).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.VALUE_OPTIONS__STRING_LITERAL, null, msgs);
      msgs = basicSetStringLiteral(newStringLiteral, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.VALUE_OPTIONS__STRING_LITERAL, newStringLiteral, newStringLiteral));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NumberLiteral getNumberLiteral()
  {
    return numberLiteral;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetNumberLiteral(NumberLiteral newNumberLiteral, NotificationChain msgs)
  {
    NumberLiteral oldNumberLiteral = numberLiteral;
    numberLiteral = newNumberLiteral;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.VALUE_OPTIONS__NUMBER_LITERAL, oldNumberLiteral, newNumberLiteral);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNumberLiteral(NumberLiteral newNumberLiteral)
  {
    if (newNumberLiteral != numberLiteral)
    {
      NotificationChain msgs = null;
      if (numberLiteral != null)
        msgs = ((InternalEObject)numberLiteral).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.VALUE_OPTIONS__NUMBER_LITERAL, null, msgs);
      if (newNumberLiteral != null)
        msgs = ((InternalEObject)newNumberLiteral).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.VALUE_OPTIONS__NUMBER_LITERAL, null, msgs);
      msgs = basicSetNumberLiteral(newNumberLiteral, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.VALUE_OPTIONS__NUMBER_LITERAL, newNumberLiteral, newNumberLiteral));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TextLiteral getTextLiteral()
  {
    return textLiteral;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTextLiteral(TextLiteral newTextLiteral, NotificationChain msgs)
  {
    TextLiteral oldTextLiteral = textLiteral;
    textLiteral = newTextLiteral;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, MyDslPackage.VALUE_OPTIONS__TEXT_LITERAL, oldTextLiteral, newTextLiteral);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTextLiteral(TextLiteral newTextLiteral)
  {
    if (newTextLiteral != textLiteral)
    {
      NotificationChain msgs = null;
      if (textLiteral != null)
        msgs = ((InternalEObject)textLiteral).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.VALUE_OPTIONS__TEXT_LITERAL, null, msgs);
      if (newTextLiteral != null)
        msgs = ((InternalEObject)newTextLiteral).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - MyDslPackage.VALUE_OPTIONS__TEXT_LITERAL, null, msgs);
      msgs = basicSetTextLiteral(newTextLiteral, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.VALUE_OPTIONS__TEXT_LITERAL, newTextLiteral, newTextLiteral));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MyDslPackage.VALUE_OPTIONS__STRING_LITERAL:
        return basicSetStringLiteral(null, msgs);
      case MyDslPackage.VALUE_OPTIONS__NUMBER_LITERAL:
        return basicSetNumberLiteral(null, msgs);
      case MyDslPackage.VALUE_OPTIONS__TEXT_LITERAL:
        return basicSetTextLiteral(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.VALUE_OPTIONS__STRING_LITERAL:
        return getStringLiteral();
      case MyDslPackage.VALUE_OPTIONS__NUMBER_LITERAL:
        return getNumberLiteral();
      case MyDslPackage.VALUE_OPTIONS__TEXT_LITERAL:
        return getTextLiteral();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.VALUE_OPTIONS__STRING_LITERAL:
        setStringLiteral((StringLiteral)newValue);
        return;
      case MyDslPackage.VALUE_OPTIONS__NUMBER_LITERAL:
        setNumberLiteral((NumberLiteral)newValue);
        return;
      case MyDslPackage.VALUE_OPTIONS__TEXT_LITERAL:
        setTextLiteral((TextLiteral)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.VALUE_OPTIONS__STRING_LITERAL:
        setStringLiteral((StringLiteral)null);
        return;
      case MyDslPackage.VALUE_OPTIONS__NUMBER_LITERAL:
        setNumberLiteral((NumberLiteral)null);
        return;
      case MyDslPackage.VALUE_OPTIONS__TEXT_LITERAL:
        setTextLiteral((TextLiteral)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.VALUE_OPTIONS__STRING_LITERAL:
        return stringLiteral != null;
      case MyDslPackage.VALUE_OPTIONS__NUMBER_LITERAL:
        return numberLiteral != null;
      case MyDslPackage.VALUE_OPTIONS__TEXT_LITERAL:
        return textLiteral != null;
    }
    return super.eIsSet(featureID);
  }

} //ValueOptionsImpl
